/***************************************************************************
 * Copyright 1998-2020 by authors (see AUTHORS.txt)                        *
 *                                                                         *
 *   This file is part of LuxCoreRender.                                   *
 *                                                                         *
 * Licensed under the Apache License, Version 2.0 (the "License");         *
 * you may not use this file except in compliance with the License.        *
 * You may obtain a copy of the License at                                 *
 *                                                                         *
 *     http://www.apache.org/licenses/LICENSE-2.0                          *
 *                                                                         *
 * Unless required by applicable law or agreed to in writing, software     *
 * distributed under the License is distributed on an "AS IS" BASIS,       *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*
 * See the License for the specific language governing permissions and     *
 * limitations under the License.                                          *
 ***************************************************************************/

// Hair BSDF after Chiang et al. 2019 "A Practical and Controllable Hair and
// Fur Model". Ported from pbrt-v3's HairBSDF (BSD-3 licensed, (c) Matt Pharr,
// Greg Humphreys, Wenzel Jakob) and adapted to the LuxCore material API:
//   - the fiber tangent comes from the strands tessellation via vertex AOV
//     layers (object space, transformed to the shading frame per hit)
//   - the azimuthal hit offset h is computed geometrically from the shading
//     normal and the outgoing direction (works for true cylinder geometry)
//   - LuxCore's "f * cos" Evaluate convention means we return pbrt's fsum
//     without the final 1/cos division
//
// Optional model "huang": Huang, Hullin & Hanika 2022 "A Microfacet-based
// Hair Scattering Model" (EGSR 2022, doi:10.1111/cgf.14588), ported from the
// Cycles reference (Apache-2.0, bsdf_principled_hair_huang.h). LuxCore
// tessellates strands into real triangle geometry, so each hit supplies the
// true azimuthal offset h and the curve-BCSDF h-integration collapses to the
// per-point surface formulation: f*cos = integrand * jac_i / cos_theta_i,
// which reduces the R lobe to a standard tilted-GGX dielectric BRDF. TT/TRT
// are evaluated by deterministic VNDF quadrature so Evaluate() remains a
// pure function of (wi, wo) for MIS. The albedo correction uses the
// single-scatter GGX-glass directional albedo LUT generated by
// dev-tools/e36_gen_huang_lut.py (same role as Cycles' ggx_glass_E).

#include <array>
#include <numeric>

#include "slg/materials/hairmat.h"
#include "slg/materials/hair_huang_lut.h"
#include "slg/materials/microfacet.h"
#include "slg/textures/fresnel/fresneltexture.h"
#include "luxrays/utils/utils.h"

using namespace luxrays;
using namespace slg;

namespace {

constexpr int pMax = 3;
constexpr float SqrtPiOver8 = 0.626657069f; // sqrt(Pi / 8)

inline float SafeSqrt(const float x) { return sqrtf(Max(0.f, x)); }
inline float SafeASin(const float x) { return asinf(Clamp(x, -1.f, 1.f)); }
inline float Fract(const float x) { return x - floorf(x); }

inline float I0(float x) {
	float val = 0.f;
	float x2i = 1.f;
	int64_t ifact = 1;
	int i4 = 1;
	// I0(x) ~= Sum_i x^(2i) / (4^i (i!)^2)
	for (int i = 0; i < 10; ++i) {
		if (i > 1) ifact *= i;
		val += x2i / (i4 * Sqr(ifact));
		x2i *= x * x;
		i4 *= 4;
	}
	return val;
}

inline float LogI0(float x) {
	if (x > 12.f)
		return x + 0.5f * (-logf(2.f * M_PI) + logf(1.f / x) + 1.f / (8.f * x));
	else
		return logf(I0(x));
}

inline float Mp(float cosThetaI, float cosThetaO, float sinThetaI,
		float sinThetaO, float v) {
	const float a = cosThetaI * cosThetaO / v;
	const float b = sinThetaI * sinThetaO / v;
	const float mp = (v <= .1f)
		? expf(LogI0(a) - b - 1.f / v + 0.6931f + logf(1.f / (2.f * v)))
		: (expf(-b) * I0(a)) / (sinhf(1.f / v) * 2.f * v);
	return mp;
}

inline float Phi(const int p, const float gammaO, const float gammaT) {
	return 2.f * p * gammaT - 2.f * gammaO + p * M_PI;
}

inline float Logistic(float x, const float s) {
	x = fabsf(x);
	return expf(-x / s) / (s * Sqr(1.f + expf(-x / s)));
}

inline float LogisticCDF(const float x, const float s) {
	return 1.f / (1.f + expf(-x / s));
}

inline float TrimmedLogistic(const float x, const float s, const float a, const float b) {
	return Logistic(x, s) / (LogisticCDF(b, s) - LogisticCDF(a, s));
}

inline float Np(float phi, const int p, const float s,
		const float gammaO, const float gammaT) {
	float dphi = phi - Phi(p, gammaO, gammaT);
	// Remap dphi to [-pi, pi]
	while (dphi > M_PI) dphi -= 2.f * M_PI;
	while (dphi < -M_PI) dphi += 2.f * M_PI;
	return TrimmedLogistic(dphi, s, -M_PI, M_PI);
}

inline float SampleTrimmedLogistic(const float u, const float s,
		const float a, const float b) {
	const float k = LogisticCDF(b, s) - LogisticCDF(a, s);
	const float x = -s * logf(1.f / (u * k + LogisticCDF(a, s)) - 1.f);
	return Clamp(x, a, b);
}

// Attenuation A_p for each scattering order p = 0..pMax
inline void Ap(const float cosThetaO, const float eta, const float h,
		const Spectrum &T, Spectrum *ap) {
	// p = 0 attenuation at initial cylinder intersection
	const float cosGammaO = SafeSqrt(1.f - h * h);
	const float cosTheta = cosThetaO * cosGammaO;
	const float f = FresnelTexture::CauchyEvaluate(eta, cosTheta);
	ap[0] = f;

	// p = 1 attenuation
	ap[1] = Sqr(1.f - f) * T;

	// Attenuation up to pMax
	for (int p = 2; p < pMax; ++p)
		ap[p] = ap[p - 1] * T * f;

	// Remaining orders of scattering
	ap[pMax] = ap[pMax - 1] * f * T / (Spectrum(1.f) - T * f);
}

// Rotate (sinThetaO, cosThetaO) by the lobe-dependent scale tilt
inline void TiltThetaO(const int p, const float *sin2k, const float *cos2k,
		const float sinThetaO, const float cosThetaO,
		float *sinThetaOp, float *cosThetaOp) {
	if (p == 0) {
		*sinThetaOp = sinThetaO * cos2k[1] - cosThetaO * sin2k[1];
		*cosThetaOp = cosThetaO * cos2k[1] + sinThetaO * sin2k[1];
	} else if (p == 1) {
		*sinThetaOp = sinThetaO * cos2k[0] + cosThetaO * sin2k[0];
		*cosThetaOp = cosThetaO * cos2k[0] - sinThetaO * sin2k[0];
	} else if (p == 2) {
		*sinThetaOp = sinThetaO * cos2k[2] + cosThetaO * sin2k[2];
		*cosThetaOp = cosThetaO * cos2k[2] - sinThetaO * sin2k[2];
	} else {
		*sinThetaOp = sinThetaO;
		*cosThetaOp = cosThetaO;
	}
	*cosThetaOp = fabsf(*cosThetaOp);
}

// Split one stratified float into two (pbrt-style demux) so the BSDF gets
// its four sample dimensions from the three values LuxCore supplies.
inline void DemuxFloat(const float u, float *a, float *b) {
	*a = Fract(u * 65536.f);
	*b = Fract(u * 4294967296.f);
}

// Shared per-hit setup for the hair frame basis (tangent + radial dir).
// Returns e1 (radial) and e2 = cross(tangent, e1).
inline void HairFrame(const Vector &T, Vector *e1, Vector *e2) {
	Vector nPerp = Vector(0.f, 0.f, 1.f) - T * T.z;
	if (nPerp.LengthSquared() < 1e-12f)
		nPerp = Vector(1.f, 0.f, 0.f) - T * T.x;
	*e1 = Normalize(nPerp);
	*e2 = Cross(T, *e1);
}

} // anonymous namespace

//------------------------------------------------------------------------------
// Huang'22 helpers. Hair frame convention (Cycles): y = strand tangent,
// x/z = azimuthal plane, directions live in the unit sphere with phi_i = 0
// for circular cross-sections.
//------------------------------------------------------------------------------

namespace huang {

inline float SinThetaT(const Vector &w) { return w.y; }
inline float CosThetaT(const Vector &w) { return sqrtf(Max(0.f, w.x * w.x + w.z * w.z)); }
inline float TanThetaT(const Vector &w) { return SinThetaT(w) / CosThetaT(w); }
inline float DirTheta(const Vector &w) { return atan2f(SinThetaT(w), CosThetaT(w)); }
inline float DirPhi(const Vector &w) { return atan2f(w.x, w.z); }
inline void SincosPhi(const Vector &w, float *s, float *c) {
	const float ct = CosThetaT(w);
	*s = w.x / ct;
	*c = w.z / ct;
}
inline bool IsCircular(const float b) { return b == 1.f; }

// gamma <-> phi conversion on the elliptical cross-section (paper Fig. 5)
inline float ToPhi(const float gamma, const float b) {
	if (IsCircular(b)) return gamma;
	return atan2f(b * sinf(gamma), cosf(gamma));
}
inline float ToGamma(const float phi, const float b) {
	if (IsCircular(b)) return phi;
	return atan2f(sinf(phi), b * cosf(phi));
}
// h = -cos_phi_i * sin_gamma + b * sin_phi_i * cos_gamma
inline float PhiToH(const float phi, const float b, const Vector &wi) {
	if (IsCircular(b)) return -sinf(phi);
	float sI, cI;
	SincosPhi(wi, &sI, &cI);
	const float gamma = ToGamma(phi, b);
	return -cI * sinf(gamma) + b * sI * cosf(gamma);
}
// Solve gamma for h = -cos_phi_i sin_gamma + b sin_phi_i cos_gamma,
// with h pre-divided by the projected radius into [-1, 1]
inline float HToGamma(const float hDivR, const float b, const Vector &wi) {
	return IsCircular(b) ? -SafeASin(hDivR) :
		atan2f(wi.z, -b * wi.x) - acosf(-hDivR);
}
// Jacobian |d_gamma/d_h|
inline float DGamDh(const float sI, const float cI, const float gamma, const float b) {
	if (IsCircular(b))
		return 1.f / Max(fabsf(cosf(gamma)), 1e-6f);
	return 1.f / Max(fabsf(cI * cosf(gamma) + b * sI * sinf(gamma)), 1e-6f);
}
// Point on the ellipse (sin_gamma, b cos_gamma)
inline Vector ToPoint(const float gamma, const float b) {
	return Vector(sinf(gamma), b * cosf(gamma), 0.f);
}
// Direction with polar angle theta (from +y) and azimuthal coordinate gamma
inline Vector SphgDir(const float theta, const float gamma, const float b) {
	const float st = sinf(theta), ct = cosf(theta);
	const float sg = sinf(gamma), cg = cosf(gamma);
	float sp, cp;
	if (IsCircular(b) || fabsf(cg) < 1e-6f) {
		sp = sg;
		cp = cg;
	} else {
		const float tanP = b * sg / cg;
		cp = Sgn(cg) / sqrtf(Sqr(tanP) + 1.f);
		sp = cp * tanP;
	}
	return Vector(sp * ct, st, cp * ct);
}
inline float ArcLength(const float e2, const float gamma) {
	return e2 == 0.f ? 1.f : sqrtf(1.f - e2 * Sqr(sinf(gamma)));
}

inline Vector RefractAngle(const Vector &i, const Vector &n,
		const float cosThetaT, const float invEta) {
	return (invEta * Dot(n, i) + cosThetaT) * n - invEta * i;
}
inline Vector ReflectDir(const Vector &i, const Vector &n) {
	return 2.f * Dot(i, n) * n - i;
}
inline bool MicrofacetVisible(const Vector &v, const Vector &m, const Vector &h) {
	return Dot(v, h) > 0.f && Dot(v, m) > 0.f;
}
inline bool MicrofacetVisible(const Vector &wi, const Vector &wo,
		const Vector &m, const Vector &h) {
	return MicrofacetVisible(wi, m, h) && MicrofacetVisible(wo, m, h);
}

// GGX terms parameterized by alpha2 = alpha^2 (Cycles convention)
inline float HuangLambda(const float alpha2, const float cosN) {
	const float c = fabsf(cosN);
	if (c < 1e-7f) return 1e30f;
	return .5f * (sqrtf(1.f + alpha2 * (1.f / (c * c) - 1.f)) - 1.f);
}
inline float HuangG(const float alpha2, const float cosI, const float cosO) {
	return 1.f / (1.f + HuangLambda(alpha2, cosI) + HuangLambda(alpha2, cosO));
}
// Combined masking-shadowing over the incoming masking (Go ratio)
inline float HuangGo(const float alpha2, const float cosNI, const float cosNO) {
	return (1.f + HuangLambda(alpha2, cosNI)) /
		(1.f + HuangLambda(alpha2, cosNI) + HuangLambda(alpha2, cosNO));
}
inline float HuangD(const float alpha2, const float cosNH) {
	const float c2 = Min(Sqr(cosNH), 1.f);
	return alpha2 / (M_PI * Sqr(1.f - c2 + alpha2 * c2));
}

// Dielectric Fresnel, also returning the transmitted cosine
inline float FresnelDielectricT(const float cosI, const float eta, float *cosT) {
	const float c = fabsf(cosI);
	const float sin2T = (1.f - c * c) / (eta * eta);
	if (sin2T >= 1.f) {
		*cosT = 0.f;
		return 1.f;
	}
	const float t = sqrtf(1.f - sin2T);
	*cosT = t;
	const float rp = (eta * c - t) / (eta * c + t);
	const float rs = (c - eta * t) / (c + eta * t);
	return .5f * (Sqr(rp) + Sqr(rs));
}
inline float FresnelDielectricC(const float cosI, const float eta) {
	const float c = fabsf(cosI);
	const float g = eta * eta - 1.f + c * c;
	if (g <= 0.f) return 1.f;
	const float gs = sqrtf(g);
	return .5f * Sqr((gs - c) / (gs + c)) *
		(1.f + Sqr(((gs + c) * c - 1.f) / ((gs - c) * c + 1.f)));
}

// Albedo correction: 1/E of a rough dielectric interface (LUT, see header)
inline float HuangEnergyScale(const float mu, const float sqrtAlpha, const float eta) {
	return 1.f / Max(Huang_GlassE(mu, sqrtAlpha, eta), 1e-4f);
}

// VNDF sample about a tilted mesonormal
inline Vector SampleWh(const float alpha, const Vector &wi, const Vector &wm,
		const float u0, const float u1) {
	Vector s, t;
	CoordinateSystem(wm, &s, &t); // arbitrary orthonormal basis around wm
	const Vector wiWm(wi.x * s.x + wi.y * s.y + wi.z * s.z,
			wi.x * t.x + wi.y * t.y + wi.z * t.z,
			wi.x * wm.x + wi.y * wm.y + wi.z * wm.z);
	const Vector whWm = GgxSampleVNDF(wiWm, alpha, alpha, u0, u1);
	return whWm.x * s + whWm.y * t + whWm.z * wm;
}

// TRRT+ approximation: geometric series of the remaining orders (Chiang'16)
inline Spectrum EvalTRRT(const float T, const float R, const Spectrum &A) {
	const float tAvg = Max(1.f - R, 1e-5f);
	const Spectrum trrt = T * Sqr(R) * tAvg * A * A * A;
	return trrt / (Spectrum(1.f) - A * (1.f - tAvg));
}

inline void ToLocal(const Vector &w, const Vector &x, const Vector &y,
		const Vector &z, Vector *out) {
	*out = Vector(Dot(w, x), Dot(w, y), Dot(w, z));
}
inline void ToGlobal(const Vector &w, const Vector &x, const Vector &y,
		const Vector &z, Vector *out) {
	*out = x * w.x + y * w.y + z * w.z;
}

// Deterministic VNDF quadrature points (Hammersley 8 / 4) replacing the
// Monte-Carlo quadrature Cycles runs inside eval_residual: Evaluate() must
// stay a pure function of (wi, wo).
constexpr int kQWh1 = 8;
constexpr int kQWh2 = 4;
constexpr float kQuadWh1[kQWh1][2] = {
	{0.125f, 0.0625f}, {0.625f, 0.1875f}, {0.375f, 0.3125f}, {0.875f, 0.4375f},
	{0.250f, 0.5625f}, {0.750f, 0.6875f}, {0.500f, 0.8125f}, {0.0625f, 0.9375f}
};
constexpr float kQuadWh2[kQWh2][2] = {
	{0.19f, 0.41f}, {0.69f, 0.83f}, {0.44f, 0.09f}, {0.94f, 0.61f}
};

} // namespace huang

//------------------------------------------------------------------------------
// HairMaterial
//------------------------------------------------------------------------------

HairMaterial::HairMaterial(TextureConstPtr frontTransp, TextureConstPtr backTransp,
		TextureConstPtr emitted, TextureConstPtr bump,
		TextureConstPtr sigmaATex, TextureConstPtr colorTex,
		TextureConstPtr eumelaninTex, TextureConstPtr pheomelaninTex,
		TextureConstPtr etaTex, TextureConstPtr betaMTex, TextureConstPtr betaNTex,
		TextureConstPtr alphaTex, TextureConstPtr roughnessTex,
		TextureConstPtr aspectRatioTex, const float rScale,
		const float ttScale, const float trtScale, const HairModel hairModel) :
		Material(frontTransp, backTransp, emitted, bump),
		sigmaA(sigmaATex), color(colorTex),
		eumelanin(eumelaninTex), pheomelanin(pheomelaninTex),
		eta(etaTex), betaM(betaMTex), betaN(betaNTex), alpha(alphaTex),
		roughness(roughnessTex), aspectRatio(aspectRatioTex),
		scaleR(rScale), scaleTT(ttScale), scaleTRT(trtScale), model(hairModel) {
}

Spectrum HairMaterial::EvalSigmaA(const HitPoint &hitPoint, const float betaN) const {
	if (sigmaA)
		return sigmaA->GetSpectrumValue(hitPoint).Clamp();

	if (color) {
		const Spectrum c = color->GetSpectrumValue(hitPoint).Clamp(0.f, 1.f);
		// SigmaAFromReflectance (Chiang 2019)
		const float denom = 5.969f - 0.215f * betaN + 2.532f * Sqr(betaN) -
				10.73f * (betaN * betaN * betaN) + 5.574f * powf(betaN, 4.f) +
				0.245f * powf(betaN, 5.f);
		Spectrum sa;
		for (u_int i = 0; i < COLOR_SAMPLES; ++i)
			sa.c[i] = Sqr(logf(Max(c.c[i], 1e-5f)) / denom);
		return sa;
	}

	// Melanin concentration model (default: brown hair 1.3 / 0)
	const float ce = eumelanin ? Max(0.f, eumelanin->GetFloatValue(hitPoint)) : 1.3f;
	const float cp = pheomelanin ? Max(0.f, pheomelanin->GetFloatValue(hitPoint)) : 0.f;
	const float eu[3] = {0.419f, 0.697f, 1.37f};
	const float ph[3] = {0.187f, 0.4f, 1.05f};
	float sa[3];
	for (int i = 0; i < 3; ++i)
		sa[i] = ce * eu[i] + cp * ph[i];
	return Spectrum(sa);
}

bool HairMaterial::SetupContext(const HitPoint &hitPoint,
		const Vector &localEyeDir, HairContext *ctx) const {
	// Strand tangent: vertex AOV (object space) -> world -> local frame
	const float tx = hitPoint.GetVertexAOV(HAIR_TANGENT_X_DATA_INDEX);
	const float ty = hitPoint.GetVertexAOV(HAIR_TANGENT_Y_DATA_INDEX);
	const float tz = hitPoint.GetVertexAOV(HAIR_TANGENT_Z_DATA_INDEX);
	Vector tObj(tx, ty, tz);
	if (tObj.LengthSquared() < 1e-12f) {
		// No strand data (e.g. material used on a regular mesh): fall back
		// to dpdv which is the fiber direction for strand-like UV layouts.
		tObj = hitPoint.dpdv;
	}
	const Vector tWorld = Normalize(hitPoint.localToWorld * tObj);
	ctx->tangent = Normalize(hitPoint.GetFrame().ToLocal(tWorld));

	const float bm = Clamp(betaM->GetFloatValue(hitPoint), 1e-2f, 1.f);
	const float bn = Clamp(betaN->GetFloatValue(hitPoint), 1e-2f, 1.f);
	const float a = alpha->GetFloatValue(hitPoint);
	ctx->eta = eta->GetFloatValue(hitPoint);
	ctx->sigma_a = EvalSigmaA(hitPoint, bn);

	if (model == HairModel::HUANG) {
		// Cuticle tilt in radians; negated to keep the Principled-Hair
		// offset convention (same sign as the Chiang path's alpha).
		ctx->tilt = -Radians(a);
		// GGX alpha follows the Cycles convention: alpha = artist roughness.
		ctx->rough = Clamp(roughness->GetFloatValue(hitPoint), 0.001f, 1.f);
		ctx->aspect = Clamp(aspectRatio ? aspectRatio->GetFloatValue(hitPoint)
				: 1.f, 0.1f, 1.f);
		const float b = ctx->aspect;

		// Azimuthal hit offset: cosine between the shading normal and the
		// direction perpendicular to both tangent and ray (Cycles' h).
		const Vector xRay = Cross(ctx->tangent, localEyeDir);
		const float xRayLen = xRay.Length();

		// Local frame X: perpendicular to the ray for circular
		// cross-sections, or aligned with the ellipse major axis (the
		// tangent-projected shading normal) otherwise; Y is the tangent.
		Vector X;
		if (huang::IsCircular(b)) {
			X = xRayLen >= 1e-8f ? xRay / xRayLen : Vector(1.f, 0.f, 0.f);
		} else {
			Vector nPerp = Vector(0.f, 0.f, 1.f) - ctx->tangent * ctx->tangent.z;
			X = nPerp.LengthSquared() < 1e-12f ?
					Vector(1.f, 0.f, 0.f) : Normalize(nPerp);
		}

		if (xRayLen < 1e-8f) {
			// Ray parallel to the fiber: azimuth is undefined
			ctx->hDivR = 0.f;
			ctx->radius = 1.f;
		} else {
			// Shading normal is (0,0,1) in the local frame
			const float h = -xRay.z / xRayLen;
			// Projected radius from the view direction, in the *ellipse*
			// frame (X = major axis) — using the ray frame here skews
			// radius for b != 1 and drops center hits (Cycles' setup).
			const float e2 = 1.f - Sqr(b);
			const float wiX = Dot(localEyeDir, X);
			const float wiZ = Dot(localEyeDir, Cross(X, ctx->tangent));
			ctx->radius = e2 == 0.f ? 1.f :
					sqrtf(1.f - e2 * Sqr(wiX) / (Sqr(wiX) + Sqr(wiZ)));
			ctx->hDivR = h / ctx->radius;
		}
		if (fabsf(ctx->hDivR) >= 1.f)
			return false;

		ctx->frameX = X;
		ctx->frameY = ctx->tangent;
		ctx->frameZ = Cross(ctx->frameX, ctx->frameY);
		huang::ToLocal(localEyeDir, ctx->frameX, ctx->frameY, ctx->frameZ,
				&ctx->wi);
		return true;
	}

	// Longitudinal variance from beta_m
	ctx->v[0] = Sqr(0.726f * bm + 0.812f * Sqr(bm) + 3.7f * powf(bm, 20.f));
	ctx->v[1] = .25f * ctx->v[0];
	ctx->v[2] = 4.f * ctx->v[0];
	ctx->v[3] = ctx->v[2];

	// Azimuthal logistic scale from beta_n
	ctx->s = SqrtPiOver8 *
			(0.265f * bn + 1.194f * Sqr(bn) + 5.372f * powf(bn, 22.f));

	// Scale tilt (alpha) terms
	ctx->sin2kAlpha[0] = sinf(Radians(a));
	ctx->cos2kAlpha[0] = SafeSqrt(1.f - Sqr(ctx->sin2kAlpha[0]));
	for (int i = 1; i < 3; ++i) {
		ctx->sin2kAlpha[i] = 2.f * ctx->cos2kAlpha[i - 1] * ctx->sin2kAlpha[i - 1];
		ctx->cos2kAlpha[i] = Sqr(ctx->cos2kAlpha[i - 1]) - Sqr(ctx->sin2kAlpha[i - 1]);
	}

	// Azimuthal offset h: sine of the angle between the hit radial
	// direction and the ray-azimuth plane. e1_wo is the azimuthal direction
	// of the outgoing ray projected perpendicular to the fiber.
	Vector e1, e2;
	HairFrame(ctx->tangent, &e1, &e2);
	Vector e1wo = localEyeDir - ctx->tangent * Dot(localEyeDir, ctx->tangent);
	if (e1wo.LengthSquared() < 1e-12f)
		e1wo = e1; // outgoing ray parallel to the fiber: h = 0
	else
		e1wo = Normalize(e1wo);
	const Vector e2wo = Cross(ctx->tangent, e1wo);
	const float h = Clamp(Dot(e1, e2wo), -1.f, 1.f);
	ctx->gammaO = SafeASin(h);

	return true;
}

Spectrum HairMaterial::f(const HitPoint &hitPoint, const HairContext &ctx,
		const Vector &localLightDir, const Vector &localEyeDir) const {
	const Vector &T = ctx.tangent;
	Vector e1, e2;
	HairFrame(T, &e1, &e2);

	// Hair coordinate terms for wo (outgoing/eye)
	const float sinThetaO = Dot(localEyeDir, T);
	const float cosThetaO = SafeSqrt(1.f - Sqr(sinThetaO));
	const float phiO = atan2f(Dot(localEyeDir, e2), Dot(localEyeDir, e1));

	// Hair coordinate terms for wi (light)
	const float sinThetaI = Dot(localLightDir, T);
	const float cosThetaI = SafeSqrt(1.f - Sqr(sinThetaI));
	const float phiI = atan2f(Dot(localLightDir, e2), Dot(localLightDir, e1));

	// cos(thetaT) for refracted ray
	const float sinThetaT = sinThetaO / ctx.eta;
	const float cosThetaT = SafeSqrt(1.f - Sqr(sinThetaT));

	// gammaT for refracted ray
	const float h = sinf(ctx.gammaO);
	const float etap = sqrtf(ctx.eta * ctx.eta - Sqr(sinThetaO)) / cosThetaO;
	const float sinGammaT = h / etap;
	const float cosGammaT = SafeSqrt(1.f - Sqr(sinGammaT));
	const float gammaT = SafeASin(sinGammaT);

	// Transmittance T of a single path through the cylinder
	const Spectrum Tt = Exp(-ctx.sigma_a * (2.f * cosGammaT / cosThetaT));

	// Evaluate hair BSDF
	const float phi = phiI - phiO;
	Spectrum ap[pMax + 1];
	Ap(cosThetaO, ctx.eta, h, Tt, ap);

	Spectrum fsum(0.f);
	for (int p = 0; p < pMax; ++p) {
		float sinThetaOp, cosThetaOp;
		TiltThetaO(p, ctx.sin2kAlpha, ctx.cos2kAlpha,
				sinThetaO, cosThetaO, &sinThetaOp, &cosThetaOp);
		fsum += Mp(cosThetaI, cosThetaOp, sinThetaI, sinThetaOp, ctx.v[p]) *
				ap[p] * Np(phi, p, ctx.s, ctx.gammaO, gammaT);
	}

	// Remaining terms after pMax
	fsum += Mp(cosThetaI, cosThetaO, sinThetaI, sinThetaO, ctx.v[pMax]) *
			ap[pMax] / (2.f * M_PI);
	// LuxCore wants f * cos: pbrt's BSDF value is fsum/|cosThetaI| so the
	// cosine-multiplied value is exactly fsum — no division needed.
	return fsum;
}

void HairMaterial::ComputeApPdf(const HairContext &ctx, const float cosThetaO,
		float *apPdf) const {
	const float sinThetaO = SafeSqrt(1.f - cosThetaO * cosThetaO);

	const float sinThetaT = sinThetaO / ctx.eta;
	const float cosThetaT = SafeSqrt(1.f - Sqr(sinThetaT));

	const float h = sinf(ctx.gammaO);
	const float etap = sqrtf(ctx.eta * ctx.eta - Sqr(sinThetaO)) / cosThetaO;
	const float sinGammaT = h / etap;
	const float cosGammaT = SafeSqrt(1.f - Sqr(sinGammaT));

	const Spectrum T = Exp(-ctx.sigma_a * (2.f * cosGammaT / cosThetaT));
	Spectrum ap[pMax + 1];
	Ap(cosThetaO, ctx.eta, h, T, ap);

	float sumY = 0.f;
	for (int i = 0; i <= pMax; ++i)
		sumY += ap[i].Y();
	for (int i = 0; i <= pMax; ++i)
		apPdf[i] = (sumY > 0.f) ? (ap[i].Y() / sumY) : 0.f;
}

// Huang'22 eval at the hit azimuth: R lobe (closed form) + residual
// TT/TRT/TRRT transport through the fiber (deterministic VNDF quadrature).
// wi = ctx.wi (eye dir in hair frame); woLight = the evaluated direction.
// Returns f * |cos(woLight . shadingNormal)| — the LuxCore Evaluate value.
//
// The Cycles curve BSDF integrates kernels K(gamma) over the cross-section
// (per-dgamma measure, via the h<->gamma jacobian). At a fixed surface hit
// the curve->surface correspondence is f*cos = K / (arc_i * cosMi): the
// projected-area hit density per dgamma. This reduces the R lobe to the
// standard slanted-GGX BRDF F*D*G/(4*|wi.m|), verified against brute-force
// microfacet simulation (dev-notes in AGENTS.md).
Spectrum HairMaterial::HuangEval(const HairContext &ctx,
		const Vector &woLight) const {
	using namespace huang;
	const float b = ctx.aspect;
	const float e2 = 1.f - Sqr(b);
	const float alpha = ctx.rough;          // GGX alpha = artist roughness
	const float alpha2 = Sqr(alpha);
	const float sqrtAlpha = sqrtf(alpha); // LUT roughness axis
	const float eta = ctx.eta;
	const float invEta = 1.f / eta;
	const Vector &wi = ctx.wi;
	const Vector &wo = woLight;

	// Azimuth of the hit point on the (possibly elliptical) cross-section
	const float gammaMi = HToGamma(ctx.hDivR, b, wi);
	const Vector wmi_ = SphgDir(0.f, gammaMi, b);   // macronormal
	const Vector wmi = SphgDir(ctx.tilt, gammaMi, b); // mesonormal (cuticle tilt)
	const float cosMi = Dot(wi, wmi);

	// Early out: the hit facet cannot see the outgoing direction
	if (cosMi <= 0.f || Dot(wo, wmi_) < 0.f || Dot(wi, wmi_) < 0.f)
		return Spectrum();

	// Curve-kernel -> surface f*cos conversion (entry projected area)
	const float arcI = ArcLength(e2, gammaMi);
	const float kSurf = 1.f / Max(arcI * cosMi, 1e-4f);

	Spectrum result(0.f);

	// ---- R lobe: standard GGX BRDF about the tilted mesonormal ----
	if (scaleR > 0.f) {
		const Vector wh = Normalize(wi + wo);
		if (MicrofacetVisible(wi, wo, wmi_, wh)) {
			const float cosMo = Dot(wo, wmi);
			const float F = FresnelDielectricC(Dot(wi, wh), eta);
			const float D = HuangD(alpha2, Dot(wmi, wh));
			const float G = HuangG(alpha2, cosMi, cosMo);
			const float scale = HuangEnergyScale(cosMi, sqrtAlpha, eta);
			result += scaleR * 0.25f * F * D * G * scale / cosMi;
		}
	}

	// ---- Residual lobes: TT / TRT / TRRT+ ----
	if (scaleTT > 0.f || scaleTRT > 0.f) {
		const Spectrum &muA = ctx.sigma_a;
		Spectrum sTT(0.f), sTRT(0.f), sTRRT(0.f);

		for (int q = 0; q < kQWh1; ++q) {
			// Entry refraction through the microfacet wh1
			const Vector wh1 = SampleWh(alpha, wi, wmi,
					kQuadWh1[q][0], kQuadWh1[q][1]);
			const float cosHi1 = Dot(wi, wh1);
			if (cosHi1 <= 0.f)
				continue;
			float cosThetaT1;
			const float F1 = FresnelDielectricT(cosHi1, eta, &cosThetaT1);
			const float T1 = 1.f - F1;
			const float scale1 = HuangEnergyScale(cosMi, sqrtAlpha, eta);
			const Vector wt = RefractAngle(wi, wh1, -cosThetaT1, invEta);
			const float phiT = DirPhi(wt);
			const float gammaMt = 2.f * ToPhi(phiT, b) - gammaMi;
			const Vector wmt = SphgDir(-ctx.tilt, gammaMt, b);
			const Vector wmt_ = SphgDir(0.f, gammaMt, b);
			const float cosMo1 = Dot(-wt, wmi);
			const float cosMi2 = Dot(-wt, wmt);
			const float G1o = HuangGo(alpha2, cosMi, cosMo1);
			if (!MicrofacetVisible(wi, -wt, wmi, wh1) ||
					!MicrofacetVisible(wi, -wt, wmi_, wh1))
				continue;

			// Chord attenuation through the fiber interior
			const float chord = IsCircular(b) ?
					2.f * cosf(gammaMi - phiT) :
					-Vector(ToPoint(gammaMi, b) - ToPoint(gammaMt + M_PI, b)).Length();
			const Spectrum At = Exp(muA * (chord / CosThetaT(wt)));
			const float scale2 = HuangEnergyScale(cosMi2, sqrtAlpha, invEta);

			// TT: exit refraction at gamma_mt
			if (scaleTT > 0.f && Dot(wo, wt) >= invEta - 1e-5f) {
				Vector wh2 = invEta * wo - wt;
				const float rcpWh2 = 1.f / wh2.Length();
				wh2 *= rcpWh2;
				const float cosMh2 = Dot(wmt, wh2);
				if (cosMh2 >= 0.f) {
					const float cosHi2 = Dot(-wt, wh2);
					const float cosHo2 = Dot(-wo, wh2);
					const float cosMo2 = Dot(-wo, wmt);
					const float T2 = (1.f - FresnelDielectricC(cosHi2, invEta)) * scale2;
					const float D2 = HuangD(alpha2, cosMh2);
					const float G2 = HuangG(alpha2, cosMi2, cosMo2);
					// cos_mi1 in the curve kernel cancels the kSurf entry
					// cosine; the exit arc factor remains.
					const Spectrum r = T1 * scale1 * T2 * D2 * G1o * G2 * At *
							cosHi2 * cosHo2 * Sqr(rcpWh2) / cosMo1 *
							(ArcLength(e2, gammaMt) / arcI);
					if (!r.Black() && !r.IsNaN())
						sTT += r;
				}
			}

			// TRT: internal reflection + exit
			if (scaleTRT > 0.f) {
				for (int q2 = 0; q2 < kQWh2; ++q2) {
					const Vector wh2 = SampleWh(alpha, -wt, wmt,
							kQuadWh2[q2][0], kQuadWh2[q2][1]);
					const float cosHi2 = Dot(-wt, wh2);
					if (cosHi2 <= 0.f)
						continue;
					const float R2 = FresnelDielectricC(cosHi2, invEta);
					const Vector wtr = ReflectDir(wt, wh2);

					if (Dot(-wtr, wo) < invEta - 1e-5f) {
						// Total internal reflection: goes to TRRT+
						sTRRT += EvalTRRT(T1, R2, At);
						continue;
					}
					if (!MicrofacetVisible(-wt, -wtr, wmt, wh2) ||
							!MicrofacetVisible(-wt, -wtr, wmt_, wh2))
						continue;

					const float phiTr = DirPhi(wtr);
					const float gammaMtr = gammaMi -
							2.f * (ToPhi(phiT, b) - ToPhi(phiTr, b)) + M_PI;
					const Vector wmtr = SphgDir(-ctx.tilt, gammaMtr, b);
					const Vector wmtr_ = SphgDir(0.f, gammaMtr, b);
					Vector wh3 = wtr + invEta * wo;
					const float rcpWh3 = 1.f / wh3.Length();
					wh3 *= rcpWh3;
					const float cosMh3 = Dot(wmtr, wh3);
					if (cosMh3 < 0.f ||
							!MicrofacetVisible(wtr, -wo, wmtr, wh3) ||
							!MicrofacetVisible(wtr, -wo, wmtr_, wh3)) {
						sTRRT += EvalTRRT(T1, R2, At);
						continue;
					}
					const float cosHi3 = Dot(wh3, wtr);
					const float cosHo3 = Dot(wh3, -wo);
					const float cosMi3 = Dot(wmtr, wtr);
					const float T3 = (1.f - FresnelDielectricC(cosHi3, invEta)) *
							HuangEnergyScale(cosMi3, sqrtAlpha, invEta);
					const float D3 = HuangD(alpha2, cosMh3);
					const Spectrum Atr = Exp(muA *
							(IsCircular(b) ?
								-2.f * fabsf(cosf(phiTr - gammaMt)) :
								-Vector(ToPoint(gammaMtr, b) - ToPoint(gammaMt, b)).Length())
							/ CosThetaT(wtr));
					const float cosMo2 = Dot(wmt, -wtr);
					const float G2o = HuangGo(alpha2, cosMi2, cosMo2);
					const float G3 = HuangG(alpha2, cosMi3, Dot(wmtr, -wo));
					// cos_mi1 cancels with kSurf; cos_mi2 remains.
					const Spectrum r = T1 * scale1 * R2 * scale2 * T3 * D3 *
							G1o * G2o * G3 * At * Atr *
							cosMi2 * cosHi3 * cosHo3 * Sqr(rcpWh3) /
							(cosMo1 * cosMo2) *
							(ArcLength(e2, gammaMtr) / arcI);
					if (!r.Black() && !r.IsNaN())
						sTRT += r;
					sTRRT += EvalTRRT(T1, R2, At);
				}
			}
		}
		sTT /= kQWh1;
		sTRT /= (kQWh1 * kQWh2);
		sTRRT /= (kQWh1 * kQWh2);

		// TRRT+ directional distribution: Chiang-style longitudinal M and
		// uniform azimuthal N (same residual model as the curve version)
		const float sinTi = SinThetaT(wi), cosTi = CosThetaT(wi);
		const float sinTo = SinThetaT(wo), cosTo = CosThetaT(wo);
		const float M = Mp(cosTi, cosTo, sinTi, sinTo, 4.f * alpha);
		const float N = 1.f / (2.f * M_PI);
		result += ((scaleTT * sTT + scaleTRT * sTRT) * Sqr(invEta) +
				sTRRT * M * N * (2.f / M_PI)) * kSurf;
	}

	return result;
}

// Huang'22 forward sampling at the hit azimuth: identical structure to the
// Cycles curve version with h fixed by the actual surface hit. Returns the
// self-normalized energy estimate (eval = sum of lobe energies), pdf = 1 —
// the same convention Cycles uses; the true directional pdf is implicit in
// the energy-proportional lobe selection.
Spectrum HairMaterial::HuangSample(const HairContext &ctx,
		Vector *woLight, const float u[8]) const {
	using namespace huang;
	const float b = ctx.aspect;
	const float alpha = ctx.rough;
	const float alpha2 = Sqr(alpha);
	const float sqrtAlpha = sqrtf(alpha);
	const float eta = ctx.eta;
	const float invEta = 1.f / eta;
	const Vector &wi = ctx.wi;

	const float gammaMi = HToGamma(ctx.hDivR, b, wi);
	const Vector wmi_ = SphgDir(0.f, gammaMi, b);
	const Vector wmi = SphgDir(ctx.tilt, gammaMi, b);
	const float cosMi1 = Dot(wmi, wi);
	if (cosMi1 < 0.f || Dot(wmi_, wi) < 0.f)
		return Spectrum();

	// Entry microfacet
	const Vector wh1 = SampleWh(alpha, wi, wmi, u[1], u[2]);
	const Vector wr = ReflectDir(wi, wh1); // = 2(wi.wh)wh - wi = Cycles -reflect
	if (!MicrofacetVisible(wi, wmi_, wh1))
		return Spectrum();
	float cosThetaT1;
	const float R1 = FresnelDielectricT(Dot(wi, wh1), eta, &cosThetaT1);
	const float scale1 = HuangEnergyScale(cosMi1, sqrtAlpha, eta);
	const float R = scaleR * R1 * scale1 *
			(MicrofacetVisible(wr, wmi_, wh1) ? 1.f : 0.f) *
			HuangGo(alpha2, cosMi1, Dot(wmi, wr));

	// TT chain
	const Vector wt = RefractAngle(wi, wh1, -cosThetaT1, invEta);
	const float phiT = DirPhi(wt);
	const float gammaMt = 2.f * ToPhi(phiT, b) - gammaMi;
	const Vector wmt = SphgDir(-ctx.tilt, gammaMt, b);
	const Vector wmt_ = SphgDir(0.f, gammaMt, b);
	const Vector wh2 = SampleWh(alpha, -wt, wmt, u[3], u[4]);
	const Vector wtr = ReflectDir(wt, wh2);
	const float cosMi2 = Dot(-wt, wmt);

	Spectrum TT(0.f), TRT(0.f), TRRT(0.f);
	Vector wtt, wtrt, wmtr, wtrrt;
	if (cosMi2 > 0.f && MicrofacetVisible(-wt, wmi_, wh1) &&
			MicrofacetVisible(-wt, wmt_, wh2)) {
		const Spectrum &muA = ctx.sigma_a;
		const float chord = IsCircular(b) ?
				2.f * cosf(phiT - gammaMi) :
				-Vector(ToPoint(gammaMi, b) - ToPoint(gammaMt + M_PI, b)).Length();
		const Spectrum At = Exp(muA * (chord / CosThetaT(wt)));
		float cosThetaT2;
		const float R2 = FresnelDielectricT(Dot(-wt, wh2), invEta, &cosThetaT2);
		const float T1 = (1.f - R1) * scale1 *
				HuangGo(alpha2, cosMi1, Dot(wmi, -wt));
		const float T2 = 1.f - R2;
		const float scale2 = HuangEnergyScale(cosMi2, sqrtAlpha, invEta);
		wtt = RefractAngle(-wt, wh2, -cosThetaT2, eta);
		if (Dot(wmt, -wtt) > 0.f && T2 > 0.f &&
				MicrofacetVisible(-wtt, wmt_, wh2)) {
			TT = scaleTT * T1 * At * T2 * scale2 *
					HuangGo(alpha2, cosMi2, Dot(wmt, -wtt));
		}

		// TRT chain
		const float phiTr = DirPhi(wtr);
		const float gammaMtr = gammaMi - 2.f * (ToPhi(phiT, b) - ToPhi(phiTr, b)) + M_PI;
		wmtr = SphgDir(-ctx.tilt, gammaMtr, b);
		const Vector wh3 = SampleWh(alpha, wtr, wmtr, u[5], u[6]);
		float cosThetaT3;
		const float R3 = FresnelDielectricT(Dot(wtr, wh3), invEta, &cosThetaT3);
		wtrt = RefractAngle(wtr, wh3, -cosThetaT3, eta);
		const float cosMi3 = Dot(wmtr, wtr);
		if (cosMi3 > 0.f) {
			const float chord2 = IsCircular(b) ?
					-2.f * fabsf(cosf(phiTr - gammaMt)) :
					-Vector(ToPoint(gammaMt, b) - ToPoint(gammaMtr, b)).Length();
			const Spectrum Atr = Exp(muA * chord2 / CosThetaT(wtr));
			const Spectrum TR = T1 * R2 * scale2 * At * Atr *
					HuangEnergyScale(cosMi3, sqrtAlpha, invEta) *
					HuangGo(alpha2, cosMi2, Dot(wmt, -wtr));
			const float T3 = 1.f - R3;
			const Vector wmtr_ = SphgDir(0.f, gammaMtr, b);
			if (T3 > 0.f && MicrofacetVisible(wtr, -wtrt, wmtr_, wh3)) {
				TRT = scaleTRT * TR * T3 *
						HuangGo(alpha2, cosMi3, Dot(wmtr, -wtrt));
			}

			// TRRT+ residual: sample the outgoing direction like Chiang's
			// residual lobe — longitudinal from the Mp inverse CDF, uniform phi
			const float randT = Max(u[7], 1e-5f);
			const float fac = 1.f + 4.f * alpha *
					logf(randT + (1.f - randT) * expf(-0.5f / alpha));
			const float uT = Fract(u[7] * 7919.f);
			const float sinTo = -fac * SinThetaT(wi) + SafeSqrt(1.f - Sqr(fac)) *
					cosf(2.f * M_PI * uT) * CosThetaT(wi);
			const float cosTo = SafeSqrt(1.f - Sqr(sinTo));
			const float phiO = 2.f * M_PI * Fract(u[0] * 104729.f + 0.31f);
			wtrrt = Vector(sinf(phiO) * cosTo, sinTo, cosf(phiO) * cosTo);

			const Spectrum Aavg = Sqrt(At * Atr);
			const float tAvg = Max(0.5f * (T2 + T3), 1e-5f);
			const Spectrum Ares = Aavg * tAvg / (Spectrum(1.f) - Aavg * (1.f - tAvg));
			TRRT = TR * R3 * Ares *
					HuangGo(alpha2, cosMi3, Dot(wmtr, ReflectDir(wtr, wh3)));
		}
	}

	// Lobe selection proportional to the estimated energies
	const float eR = R;
	const float eTT = TT.Y();
	const float eTRT = TRT.Y();
	const float eTRRT = TRRT.Y();
	const float total = eR + eTT + eTRT + eTRRT;
	if (total <= 0.f)
		return Spectrum();

	float sel = u[0] * total;
	Vector localO;
	Spectrum eval;
	if (sel < eR) {
		localO = wr;
		eval = Spectrum(total);
	} else if (sel < eR + eTT) {
		localO = wtt;
		eval = TT * (total / eTT);
	} else if (sel < eR + eTT + eTRT) {
		localO = wtrt;
		eval = TRT * (total / eTRT);
	} else {
		localO = wtrrt;
		eval = TRRT * (total / eTRRT);
	}
	*woLight = localO;
	return eval;
}

Spectrum HairMaterial::Albedo(const HitPoint &hitPoint) const {
	HairContext ctx;
	if (!SetupContext(hitPoint, Vector(0.f, 0.f, 1.f), &ctx))
		return Spectrum();

	if (model == HairModel::HUANG) {
		// Single-scattering albedo at normal incidence for display purposes:
		// the R lobe's directional albedo is captured by the energy LUT.
		const float cosMi = 1.f;
		return Spectrum(Clamp(scaleR *
				huang::HuangEnergyScale(cosMi, ctx.rough, ctx.eta) +
				scaleTT + scaleTRT, 0.f, 1.f));
	}

	float apPdf[pMax + 1];
	ComputeApPdf(ctx, 1.f, apPdf);
	float sum = 0.f;
	for (int i = 0; i <= pMax; ++i)
		sum += apPdf[i];
	return Spectrum(Clamp(sum * 0.5f, 0.f, 1.f));
}

Spectrum HairMaterial::Evaluate(const HitPoint &hitPoint,
		const Vector &localLightDir, const Vector &localEyeDir,
		BSDFEvent *event, float *directPdfW, float *reversePdfW) const {
	HairContext ctx;
	if (!SetupContext(hitPoint, localEyeDir, &ctx)) {
		*event = NONE;
		return Spectrum();
	}

	Spectrum result;
	if (model == HairModel::HUANG) {
		Vector woH;
		huang::ToLocal(localLightDir, ctx.frameX, ctx.frameY, ctx.frameZ, &woH);
		result = HuangEval(ctx, woH);
	} else {
		result = f(hitPoint, ctx, localLightDir, localEyeDir);
	}
	if (result.Black()) {
		*event = NONE;
		return Spectrum();
	}

	*event = GLOSSY | REFLECT | TRANSMIT;

	if (directPdfW) {
		if (model == HairModel::HUANG) {
			// Huang uses energy-proportional lobe selection: the estimator is
			// self-normalized (f/pdf = eval) with unit directional pdf.
			*directPdfW = 1.f;
			if (reversePdfW)
				*reversePdfW = 1.f;
			return result;
		}
		float apPdf[pMax + 1];
		const float sinThetaO = Dot(localEyeDir, ctx.tangent);
		const float cosThetaO = SafeSqrt(1.f - Sqr(sinThetaO));
		const float sinThetaI = Dot(localLightDir, ctx.tangent);
		const float cosThetaI = SafeSqrt(1.f - Sqr(sinThetaI));
		ComputeApPdf(ctx, cosThetaO, apPdf);

		Vector e1, e2;
		HairFrame(ctx.tangent, &e1, &e2);
		const float phiO = atan2f(Dot(localEyeDir, e2), Dot(localEyeDir, e1));
		const float phiI = atan2f(Dot(localLightDir, e2), Dot(localLightDir, e1));
		const float phi = phiI - phiO;

		const float h = sinf(ctx.gammaO);
		const float etap = sqrtf(ctx.eta * ctx.eta - Sqr(sinThetaO)) / cosThetaO;
		const float sinGammaT = h / etap;
		const float gammaT = SafeASin(sinGammaT);

		float pdf = 0.f;
		for (int p = 0; p < pMax; ++p) {
			float sinThetaOp, cosThetaOp;
			TiltThetaO(p, ctx.sin2kAlpha, ctx.cos2kAlpha,
					sinThetaO, cosThetaO, &sinThetaOp, &cosThetaOp);
			pdf += Mp(cosThetaI, cosThetaOp, sinThetaI, sinThetaOp, ctx.v[p]) *
					apPdf[p] * Np(phi, p, ctx.s, ctx.gammaO, gammaT);
		}
		pdf += Mp(cosThetaI, cosThetaO, sinThetaI, sinThetaO, ctx.v[pMax]) *
				apPdf[pMax] * (1.f / (2.f * M_PI));
		*directPdfW = pdf;
	}
	if (reversePdfW)
		*reversePdfW = *directPdfW; // the hair BSDF is reciprocal here

	return result;
}

Spectrum HairMaterial::Sample(const HitPoint &hitPoint,
		const Vector &localFixedDir, Vector *localSampledDir,
		const float u0, const float u1, const float passThroughEvent,
		float *pdfW, BSDFEvent *event) const {
	HairContext ctx;
	if (!SetupContext(hitPoint, localFixedDir, &ctx)) {
		*event = NONE;
		return Spectrum();
	}

	const Vector &T = ctx.tangent;
	Vector e1, e2;
	HairFrame(T, &e1, &e2);

	if (model == HairModel::HUANG) {
		float u[8];
		DemuxFloat(u0, &u[0], &u[1]);
		DemuxFloat(u1, &u[2], &u[3]);
		DemuxFloat(passThroughEvent, &u[4], &u[5]);
		DemuxFloat(Fract(u0 * 7919.f + u1 * 104729.f + 0.31f), &u[6], &u[7]);

		Vector woH;
		const Spectrum eval = HuangSample(ctx, &woH, u);
		if (eval.Black())
			return Spectrum();

		*localSampledDir = woH.x * ctx.frameX + woH.y * ctx.frameY +
				woH.z * ctx.frameZ;
		// Self-normalized estimator: the returned spectrum is the full
		// eval; the directional pdf is implicit (unit) as in Cycles.
		*pdfW = 1.f;
		*event = GLOSSY | REFLECT | TRANSMIT;
		return eval;
	}

	const float sinThetaO = Dot(localFixedDir, T);
	const float cosThetaO = SafeSqrt(1.f - Sqr(sinThetaO));
	const float phiO = atan2f(Dot(localFixedDir, e2), Dot(localFixedDir, e1));

	// Four sample dimensions from the three supplied values
	float u[2][2];
	DemuxFloat(u0, &u[0][0], &u[0][1]);
	DemuxFloat(u1, &u[1][0], &u[1][1]);
	(void)passThroughEvent;

	// Choose the lobe p from the Ap pdf
	float apPdf[pMax + 1];
	ComputeApPdf(ctx, cosThetaO, apPdf);
	int p;
	float sel = u[0][0];
	for (p = 0; p < pMax; ++p) {
		if (sel < apPdf[p]) break;
		sel -= apPdf[p];
	}

	float sinThetaOp, cosThetaOp;
	TiltThetaO(p, ctx.sin2kAlpha, ctx.cos2kAlpha,
			sinThetaO, cosThetaO, &sinThetaOp, &cosThetaOp);

	// Sample M_p -> thetaI
	const float u10 = Max(u[1][0], 1e-5f);
	const float cosTheta =
			1.f + ctx.v[p] * logf(u10 + (1.f - u10) * expf(-2.f / ctx.v[p]));
	const float sinTheta = SafeSqrt(1.f - Sqr(cosTheta));
	const float cosPhi = cosf(2.f * M_PI * u[1][1]);
	const float sinThetaI = -cosTheta * sinThetaOp + sinTheta * cosPhi * cosThetaOp;
	const float cosThetaI = SafeSqrt(1.f - Sqr(sinThetaI));

	// Sample N_p -> dphi
	const float h = sinf(ctx.gammaO);
	const float etap = sqrtf(ctx.eta * ctx.eta - Sqr(sinThetaO)) / cosThetaO;
	const float sinGammaT = h / etap;
	const float gammaT = SafeASin(sinGammaT);
	float dphi;
	if (p < pMax)
		dphi = Phi(p, ctx.gammaO, gammaT) +
				SampleTrimmedLogistic(u[0][1], ctx.s, -M_PI, M_PI);
	else
		dphi = 2.f * M_PI * u[0][1];

	const float phiI = phiO + dphi;
	*localSampledDir = sinThetaI * T +
			cosThetaI * cosf(phiI) * e1 + cosThetaI * sinf(phiI) * e2;

	// Pdf for the sampled direction
	float pdf = 0.f;
	for (int pp = 0; pp < pMax; ++pp) {
		float stp, ctp;
		TiltThetaO(pp, ctx.sin2kAlpha, ctx.cos2kAlpha,
				sinThetaO, cosThetaO, &stp, &ctp);
		pdf += Mp(cosThetaI, ctp, sinThetaI, stp, ctx.v[pp]) *
				apPdf[pp] * Np(dphi, pp, ctx.s, ctx.gammaO, gammaT);
	}
	pdf += Mp(cosThetaI, cosThetaO, sinThetaI, sinThetaO, ctx.v[pMax]) *
			apPdf[pMax] * (1.f / (2.f * M_PI));
	*pdfW = pdf;
	if (pdf <= 0.f)
		return Spectrum();

	*event = (p == 0) ? (GLOSSY | REFLECT) : (GLOSSY | TRANSMIT);

	return f(hitPoint, ctx, *localSampledDir, localFixedDir) / pdf;
}

void HairMaterial::Pdf(const HitPoint &hitPoint,
		const Vector &localLightDir, const Vector &localEyeDir,
		float *directPdfW, float *reversePdfW) const {
	HairContext ctx;
	if (!SetupContext(hitPoint, localEyeDir, &ctx)) {
		if (directPdfW) *directPdfW = 0.f;
		if (reversePdfW) *reversePdfW = 0.f;
		return;
	}

	if (model == HairModel::HUANG) {
		// Self-normalized sampler: unit directional pdf (see Sample()).
		if (directPdfW) *directPdfW = 1.f;
		if (reversePdfW) *reversePdfW = 1.f;
		return;
	}

	const Vector &T = ctx.tangent;
	Vector e1, e2;
	HairFrame(T, &e1, &e2);

	const float sinThetaO = Dot(localEyeDir, T);
	const float cosThetaO = SafeSqrt(1.f - Sqr(sinThetaO));
	const float phiO = atan2f(Dot(localEyeDir, e2), Dot(localEyeDir, e1));
	const float sinThetaI = Dot(localLightDir, T);
	const float cosThetaI = SafeSqrt(1.f - Sqr(sinThetaI));
	const float phiI = atan2f(Dot(localLightDir, e2), Dot(localLightDir, e1));

	const float h = sinf(ctx.gammaO);
	const float etap = sqrtf(ctx.eta * ctx.eta - Sqr(sinThetaO)) / cosThetaO;
	const float sinGammaT = h / etap;
	const float gammaT = SafeASin(sinGammaT);

	float apPdf[pMax + 1];
	ComputeApPdf(ctx, cosThetaO, apPdf);

	const float phi = phiI - phiO;
	float pdf = 0.f;
	for (int p = 0; p < pMax; ++p) {
		float sinThetaOp, cosThetaOp;
		TiltThetaO(p, ctx.sin2kAlpha, ctx.cos2kAlpha,
				sinThetaO, cosThetaO, &sinThetaOp, &cosThetaOp);
		pdf += Mp(cosThetaI, cosThetaOp, sinThetaI, sinThetaOp, ctx.v[p]) *
				apPdf[p] * Np(phi, p, ctx.s, ctx.gammaO, gammaT);
	}
	pdf += Mp(cosThetaI, cosThetaO, sinThetaI, sinThetaO, ctx.v[pMax]) *
			apPdf[pMax] * (1.f / (2.f * M_PI));

	if (directPdfW) *directPdfW = pdf;
	if (reversePdfW) *reversePdfW = pdf;
}

void HairMaterial::AddReferencedTextures(std::unordered_set<const Texture *> &referencedTexs) const {
	Material::AddReferencedTextures(referencedTexs);
	if (sigmaA) sigmaA->AddReferencedTextures(referencedTexs);
	if (color) color->AddReferencedTextures(referencedTexs);
	if (eumelanin) eumelanin->AddReferencedTextures(referencedTexs);
	if (pheomelanin) pheomelanin->AddReferencedTextures(referencedTexs);
	eta->AddReferencedTextures(referencedTexs);
	betaM->AddReferencedTextures(referencedTexs);
	betaN->AddReferencedTextures(referencedTexs);
	alpha->AddReferencedTextures(referencedTexs);
	roughness->AddReferencedTextures(referencedTexs);
	aspectRatio->AddReferencedTextures(referencedTexs);
}

void HairMaterial::UpdateTextureReferences(TextureConstRef oldTex, TextureRef newTex) {
	Material::UpdateTextureReferences(oldTex, newTex);
	if (sigmaA == &oldTex) sigmaA = &newTex;
	if (color == &oldTex) color = &newTex;
	if (eumelanin == &oldTex) eumelanin = &newTex;
	if (pheomelanin == &oldTex) pheomelanin = &newTex;
	if (eta == &oldTex) eta = &newTex;
	if (betaM == &oldTex) betaM = &newTex;
	if (betaN == &oldTex) betaN = &newTex;
	if (alpha == &oldTex) alpha = &newTex;
	if (roughness == &oldTex) roughness = &newTex;
	if (aspectRatio == &oldTex) aspectRatio = &newTex;
}

PropertiesUPtr HairMaterial::ToProperties(const ImageMapCache &imgMapCache,
		const bool useRealFileName) const {
	PropertiesUPtr props = std::make_unique<Properties>();

	props->Set(Material::ToProperties(imgMapCache, useRealFileName));
	props->Set(Property("type")("hairmat"));
	if (sigmaA) props->Set(Property("sigma_a")(sigmaA->GetSDLValue()));
	if (color) props->Set(Property("color")(color->GetSDLValue()));
	if (eumelanin) props->Set(Property("eumelanin")(eumelanin->GetSDLValue()));
	if (pheomelanin) props->Set(Property("pheomelanin")(pheomelanin->GetSDLValue()));
	props->Set(Property("eta")(eta->GetSDLValue()));
	props->Set(Property("beta_m")(betaM->GetSDLValue()));
	props->Set(Property("beta_n")(betaN->GetSDLValue()));
	props->Set(Property("alpha")(alpha->GetSDLValue()));
	props->Set(Property("model")(model == HairModel::HUANG ? "huang" : "chiang"));
	props->Set(Property("roughness")(roughness->GetSDLValue()));
	props->Set(Property("aspectratio")(aspectRatio->GetSDLValue()));
	props->Set(Property("scale_r")(scaleR));
	props->Set(Property("scale_tt")(scaleTT));
	props->Set(Property("scale_trt")(scaleTRT));

	return props;
}
