#!/usr/bin/env python3
"""cl2msl: engine-embedded .cl -> MSL translator for the Metal device.

Invoked by MetalDevice::CompileProgram as:
    python3 cl2msl.py <outMSL> <outJSON> <param> <param> ...
with the OpenCL program source on stdin (the same assembled .cl string
the OpenCL/CUDA backends compile). <param>s are the -D style compile
options the engine passes (RenderEngine type, epsilon bounds, BVH page
counts, sampler selection...).

Emits:
  <outMSL>  - the Metal Shading Language source (newLibraryWithSource)
  <outJSON> - per-kernel argument marshalling map:
     {kernelName: {scalars: [(name,type),...],          -> KernelScalarsN
                   direct: [(name, head),...],           -> [[buffer(N)]] in order
                   table: [(name, head),...]}}           -> KernelPtrsN fields in order
     plus "__structs__": {name: field bytes} for C++ mirroring.

The rules are the metal-poc msl_rewriter.py set, proven on M5 Pro
(full 139-file engine kernel set compiles; converge/scene renders PASS).
"""
import json
import re
import subprocess
import sys
from pathlib import Path

# {kernel_name: {scalar_fields: [...], ptr_fields: [(head, name), ...],
#                direct_fields: [(head, name), ...]}}
KERNEL_LAYOUTS = {}
# direct/table split as the emitted signature actually binds it
# (filled during rule_kernel_buffer_attrs; consumed by the record)
_split_direct = {}
_split_table = {}

SHIM = """\
// ---- CL->MSL compatibility shim (auto-generated by msl_rewriter.py) ----
#define OPENCL_FORCE_INLINE inline
// MSL has no extern function objects: every function is inlinable
#define OPENCL_FORCE_NOT_INLINE inline
#define LUXRAYS_OPENCL_DEVICE 1
#define LUXRAYS_OPENCL_KERNEL 1
#define SLG_OPENCL_KERNEL 1
#ifndef PARAM_RAY_EPSILON_MIN
#define PARAM_RAY_EPSILON_MIN 1e-5f
#endif
#ifndef PARAM_RAY_EPSILON_MAX
#define PARAM_RAY_EPSILON_MAX 1e-1f
#endif
#define NULL nullptr
#define restrict
#define MAKE_FLOAT2(x, y) (float2(x, y))
#define MAKE_FLOAT3(x, y, z) (float3(x, y, z))
#define MAKE_FLOAT4(x, y, z, w) (float4(x, y, z, w))
#define ZERO (0.0f)

// C99 math -> metal::
#define log(x) metal::log(x)
#define exp(x) metal::exp(x)
#define pow(x, y) metal::pow(x, y)
#define sqrt(x) metal::sqrt(x)
#define sqrtf(x) metal::sqrt(x)
#define clamp(x, a, b) metal::clamp(x, a, b)
#define sin(x) metal::sin(x)
#define cos(x) metal::cos(x)
#define tan(x) metal::tan(x)
#define atan2(y, x) metal::atan2(y, x)
#define floor(x) metal::floor(x)
#define ceil(x) metal::ceil(x)
#define fabs(x) metal::fabs(x)
#define fabsf(x) metal::fabs(x)
#define fmin(x, y) metal::fmin(x, y)
#define fmax(x, y) metal::fmax(x, y)
#define min(x, y) metal::min(x, y)
#define max(x, y) metal::max(x, y)
#define fmod(x, y) metal::fmod(x, y)
#define mix(x, y, a) metal::mix(x, y, a)
#define dot(x, y) metal::dot(x, y)
#define cross(x, y) metal::cross(x, y)
#define normalize(x) metal::normalize(x)
#define length(x) metal::length(x)
#define rsqrt(x) metal::rsqrt(x)
#define acos(x) metal::acos(x)
#define asin(x) metal::asin(x)
#define atan(x) metal::atan(x)
#define sinh(x) metal::sinh(x)
#define cosh(x) metal::cosh(x)
#define tanh(x) metal::tanh(x)
#define exp2(x) metal::exp2(x)
#define log2(x) metal::log2(x)
#define exp10(x) metal::pow(x, 10.0f)
#define pown(x, n) metal::pow(x, float(n))
#define round(x) metal::rint(x)
#define rint(x) metal::rint(x)
#define trunc(x) metal::trunc(x)
#define sign(x) metal::sign(x)
#define signbit(x) (metal::signbit(x))
#define isnan(x) (metal::isnan(x))
#define isinf(x) (metal::isinf(x))
#define isfinite(x) (metal::isfinite(x))
#define isequal(x, y) ((x) == (y))
#define isless(x, y) ((x) < (y))
#define islessequal(x, y) ((x) <= (y))
#define fract(x) (x - metal::floor(x))
#define mad(a, b, c) metal::fma(a, b, c)
#define fma(a, b, c) metal::fma(a, b, c)
#define select(a, b, c) metal::select(a, b, c)
#define all(x) metal::all(x)
#define any(x) metal::any(x)
#define TO_FLOAT3(x) ((float3)(x))
#define atanh(x) metal::atanh(x)

// OpenCL work-item builtins. The kernel-signature rewriter passes gid
// via thread_position_in_grid in kernels; this definition satisfies
// references from non-kernel helpers for the compile experiment
// (engines inject the real value at dispatch time).
inline size_t get_global_id(uint d) {
    // placeholder identity for the experiment: real integration passes
    // the grid position; helpers that call this in kernels get the
    // rewritten 'gid' from the kernel-signature pass
    thread size_t _experimental_gid = 0;
    return _experimental_gid;
}

// Work-group builtins: like get_global_id, the REAL values are injected
// by the kernel-signature pass as lid_/lsize_/gridid_ parameters; these
// stubs only satisfy references from non-kernel helpers (returning the
// single-work-item values).
inline size_t get_local_id(uint d) { return 0; }
inline size_t get_local_size(uint d) { return 1; }
inline size_t get_group_id(uint d) { return 0; }
inline size_t get_num_groups(uint d) { return 1; }

// Work-group barrier (film tonemap reduce kernels)
#define CLK_LOCAL_MEM_FENCE 1
#define CLK_GLOBAL_MEM_FENCE 2
#define barrier(f) metal::threadgroup_barrier(metal::mem_flags::mem_threadgroup)

// OpenCL native_* fast math. NOTE: these chain through the math macros
// above (which append the metal:: prefix) - spelling 'metal::exp' here
// would make cpp re-expand 'exp' inside the replacement, yielding
// 'metal::metal::exp'.
#define native_powr(x, y) pow(x, y)
#define native_exp(x) exp(x)
#define native_log(x) log(x)
#define native_sin(x) sin(x)
#define native_cos(x) cos(x)
#define native_sqrt(x) sqrt(x)
#define native_rsqrt(x) rsqrt(x)
#define native_divide(x, y) ((x) / (y))
#define native_recip(x) (1.0f / (x))

// Half-float loads: Metal exposes half types
inline float vload_half(size_t o, const device half *p) { (void)o; return (float)p[0]; }
inline float vload_half(size_t o, const thread half *p) { (void)o; return (float)p[0]; }
inline void vstore_half(float v, size_t o, device half *p) { (void)o; p[0] = (half)v; }

inline uint atomic_inc(device metal::atomic_uint *a) { return metal::atomic_fetch_add_explicit(a, 1u, metal::memory_order_relaxed); }
inline uint atomic_inc(device uint *p) {
    device metal::atomic_uint *ap = reinterpret_cast<device metal::atomic_uint *>(p);
    return metal::atomic_fetch_add_explicit(ap, 1u, metal::memory_order_relaxed);
}

inline float2 vload2(size_t o, const device float *p) { (void)o; return *(const device float2 *)p; }
inline float3 vload3(size_t o, const device float *p) { (void)o; return *(const device float3 *)p; }
inline float4 vload4(size_t o, const device float *p) { (void)o; return *(const device float4 *)p; }
inline void vstore2(float2 v, size_t o, device float *p) { (void)o; *(device float2 *)p = v; }
inline void vstore3(float3 v, size_t o, device float *p) { (void)o; *(device float3 *)p = v; }
inline void vstore4(float4 v, size_t o, device float *p) { (void)o; *(device float4 *)p = v; }
inline float2 vload2(size_t o, const thread float *p) { (void)o; return *(const thread float2 *)p; }
inline float3 vload3(size_t o, const thread float *p) { (void)o; return *(const thread float3 *)p; }
inline float4 vload4(size_t o, const thread float *p) { (void)o; return *(const thread float4 *)p; }
inline void vstore2(float2 v, size_t o, thread float *p) { (void)o; *(thread float2 *)p = v; }
inline void vstore3(float3 v, size_t o, thread float *p) { (void)o; *(thread float3 *)p = v; }
inline void vstore4(float4 v, size_t o, thread float *p) { (void)o; *(thread float4 *)p = v; }

inline uint as_uint(float x) { return as_type<uint>(x); }
inline int as_int(float x) { return as_type<int>(x); }
inline float as_float(uint x) { return as_type<float>(x); }

inline uint atomic_cmpxchg(device uint *p, uint expected, uint desired) {
    device metal::atomic_uint *ap = reinterpret_cast<device metal::atomic_uint *>(p);
    uint current = expected;
    metal::atomic_compare_exchange_weak_explicit(ap, &current, desired,
        metal::memory_order_relaxed, metal::memory_order_relaxed);
    return current;
}
inline int atomic_cmpxchg(device int *p, int expected, int desired) {
    device metal::atomic_int *ap = reinterpret_cast<device metal::atomic_int *>(p);
    int current = expected;
    metal::atomic_compare_exchange_weak_explicit(ap, &current, desired,
        metal::memory_order_relaxed, metal::memory_order_relaxed);
    return current;
}
// ---- end shim ----

"""


STRUCT_TYPES = [
    "Seed", "Frame", "Matrix4x4", "Quaternion", "Transform",
    "MotionSystem", "Triangle", "Mesh", "ExtMesh",
    "BSDF", "Ray", "RayHit", "UV", "Spectrum",
    # MNEE solver working types (pathoclbase_funcs.cl): scalar-pointer
    # parameters stay legal on OpenCL (private) and get 'thread' on Metal
    "MneeVtx",
]

SHIM = """\
// ---- CL->MSL compatibility shim (auto-generated by msl_rewriter.py) ----
#define OPENCL_FORCE_INLINE inline
// MSL has no extern function objects: every function is inlinable
#define OPENCL_FORCE_NOT_INLINE inline
#define LUXRAYS_OPENCL_DEVICE 1
#define LUXRAYS_OPENCL_KERNEL 1
#define SLG_OPENCL_KERNEL 1
#ifndef PARAM_RAY_EPSILON_MIN
#define PARAM_RAY_EPSILON_MIN 1e-5f
#endif
#ifndef PARAM_RAY_EPSILON_MAX
#define PARAM_RAY_EPSILON_MAX 1e-1f
#endif
#define NULL nullptr
#define restrict
#define MAKE_FLOAT2(x, y) (float2(x, y))
#define MAKE_FLOAT3(x, y, z) (float3(x, y, z))
#define MAKE_FLOAT4(x, y, z, w) (float4(x, y, z, w))
#define ZERO (0.0f)

// C99 math -> metal::
#define log(x) metal::log(x)
#define exp(x) metal::exp(x)
#define pow(x, y) metal::pow(x, y)
#define sqrt(x) metal::sqrt(x)
#define sqrtf(x) metal::sqrt(x)
#define clamp(x, a, b) metal::clamp(x, a, b)
#define sin(x) metal::sin(x)
#define cos(x) metal::cos(x)
#define tan(x) metal::tan(x)
#define atan2(y, x) metal::atan2(y, x)
#define floor(x) metal::floor(x)
#define ceil(x) metal::ceil(x)
#define fabs(x) metal::fabs(x)
#define fabsf(x) metal::fabs(x)
#define fmin(x, y) metal::fmin(x, y)
#define fmax(x, y) metal::fmax(x, y)
#define min(x, y) metal::min(x, y)
#define max(x, y) metal::max(x, y)
#define fmod(x, y) metal::fmod(x, y)
#define mix(x, y, a) metal::mix(x, y, a)
#define dot(x, y) metal::dot(x, y)
#define cross(x, y) metal::cross(x, y)
#define normalize(x) metal::normalize(x)
#define length(x) metal::length(x)
#define rsqrt(x) metal::rsqrt(x)
#define acos(x) metal::acos(x)
#define asin(x) metal::asin(x)
#define atan(x) metal::atan(x)
#define sinh(x) metal::sinh(x)
#define cosh(x) metal::cosh(x)
#define tanh(x) metal::tanh(x)
#define exp2(x) metal::exp2(x)
#define log2(x) metal::log2(x)
#define exp10(x) metal::pow(x, 10.0f)
#define pown(x, n) metal::pow(x, float(n))
#define round(x) metal::rint(x)
#define rint(x) metal::rint(x)
#define trunc(x) metal::trunc(x)
#define sign(x) metal::sign(x)
#define signbit(x) (metal::signbit(x))
#define isnan(x) (metal::isnan(x))
#define isinf(x) (metal::isinf(x))
#define isfinite(x) (metal::isfinite(x))
#define isequal(x, y) ((x) == (y))
#define isless(x, y) ((x) < (y))
#define islessequal(x, y) ((x) <= (y))
#define fract(x) (x - metal::floor(x))
#define mad(a, b, c) metal::fma(a, b, c)
#define fma(a, b, c) metal::fma(a, b, c)
#define select(a, b, c) metal::select(a, b, c)
#define all(x) metal::all(x)
#define any(x) metal::any(x)
#define TO_FLOAT3(x) ((float3)(x))
#define atanh(x) metal::atanh(x)

// OpenCL work-item builtins. The kernel-signature rewriter passes gid
// via thread_position_in_grid in kernels; this definition satisfies
// references from non-kernel helpers for the compile experiment
// (engines inject the real value at dispatch time).
inline size_t get_global_id(uint d) {
    // placeholder identity for the experiment: real integration passes
    // the grid position; helpers that call this in kernels get the
    // rewritten 'gid' from the kernel-signature pass
    thread size_t _experimental_gid = 0;
    return _experimental_gid;
}

// Work-group builtins: like get_global_id, the REAL values are injected
// by the kernel-signature pass as lid_/lsize_/gridid_ parameters; these
// stubs only satisfy references from non-kernel helpers (returning the
// single-work-item values).
inline size_t get_local_id(uint d) { return 0; }
inline size_t get_local_size(uint d) { return 1; }
inline size_t get_group_id(uint d) { return 0; }
inline size_t get_num_groups(uint d) { return 1; }

// Work-group barrier (film tonemap reduce kernels)
#define CLK_LOCAL_MEM_FENCE 1
#define CLK_GLOBAL_MEM_FENCE 2
#define barrier(f) metal::threadgroup_barrier(metal::mem_flags::mem_threadgroup)

// OpenCL native_* fast math. NOTE: these chain through the math macros
// above (which append the metal:: prefix) - spelling 'metal::exp' here
// would make cpp re-expand 'exp' inside the replacement, yielding
// 'metal::metal::exp'.
#define native_powr(x, y) pow(x, y)
#define native_exp(x) exp(x)
#define native_log(x) log(x)
#define native_sin(x) sin(x)
#define native_cos(x) cos(x)
#define native_sqrt(x) sqrt(x)
#define native_rsqrt(x) rsqrt(x)
#define native_divide(x, y) ((x) / (y))
#define native_recip(x) (1.0f / (x))

// Half-float loads: Metal exposes half types
inline float vload_half(size_t o, const device half *p) { (void)o; return (float)p[0]; }
inline float vload_half(size_t o, const thread half *p) { (void)o; return (float)p[0]; }
inline void vstore_half(float v, size_t o, device half *p) { (void)o; p[0] = (half)v; }

inline uint atomic_inc(device metal::atomic_uint *a) { return metal::atomic_fetch_add_explicit(a, 1u, metal::memory_order_relaxed); }
inline uint atomic_inc(device uint *p) {
    device metal::atomic_uint *ap = reinterpret_cast<device metal::atomic_uint *>(p);
    return metal::atomic_fetch_add_explicit(ap, 1u, metal::memory_order_relaxed);
}

inline float2 vload2(size_t o, const device float *p) { (void)o; return *(const device float2 *)p; }
inline float3 vload3(size_t o, const device float *p) { (void)o; return *(const device float3 *)p; }
inline float4 vload4(size_t o, const device float *p) { (void)o; return *(const device float4 *)p; }
inline void vstore2(float2 v, size_t o, device float *p) { (void)o; *(device float2 *)p = v; }
inline void vstore3(float3 v, size_t o, device float *p) { (void)o; *(device float3 *)p = v; }
inline void vstore4(float4 v, size_t o, device float *p) { (void)o; *(device float4 *)p = v; }
inline float2 vload2(size_t o, const thread float *p) { (void)o; return *(const thread float2 *)p; }
inline float3 vload3(size_t o, const thread float *p) { (void)o; return *(const thread float3 *)p; }
inline float4 vload4(size_t o, const thread float *p) { (void)o; return *(const thread float4 *)p; }
inline void vstore2(float2 v, size_t o, thread float *p) { (void)o; *(thread float2 *)p = v; }
inline void vstore3(float3 v, size_t o, thread float *p) { (void)o; *(thread float3 *)p = v; }
inline void vstore4(float4 v, size_t o, thread float *p) { (void)o; *(thread float4 *)p = v; }

inline uint as_uint(float x) { return as_type<uint>(x); }
inline int as_int(float x) { return as_type<int>(x); }
inline float as_float(uint x) { return as_type<float>(x); }

inline uint atomic_cmpxchg(device uint *p, uint expected, uint desired) {
    device metal::atomic_uint *ap = reinterpret_cast<device metal::atomic_uint *>(p);
    uint current = expected;
    metal::atomic_compare_exchange_weak_explicit(ap, &current, desired,
        metal::memory_order_relaxed, metal::memory_order_relaxed);
    return current;
}
inline int atomic_cmpxchg(device int *p, int expected, int desired) {
    device metal::atomic_int *ap = reinterpret_cast<device metal::atomic_int *>(p);
    int current = expected;
    metal::atomic_compare_exchange_weak_explicit(ap, &current, desired,
        metal::memory_order_relaxed, metal::memory_order_relaxed);
    return current;
}
// ---- end shim ----

"""


def clean_lines(text: str) -> str:
    out = []
    for line in text.splitlines():
        if line.startswith("#line") or line.startswith("#include"):
            continue
        out.append(line)
    return "\n".join(out)


def rule_vector_compound_literal(body: str) -> str:
    # OpenCL (floatN)(a, b, ...) is a compound literal; Metal parses the
    # same text as a C-style cast of a comma expression, i.e. a scalar
    # splat of the LAST argument. Measured 2026-09: (float4)(87,88,89,90)
    # stored (90,90,90,90) on the Metal backend (host readback + in-kernel
    # read-after-write both confirmed), silently corrupting the path-guiding
    # record store, Guide_BinDir and the cosine helper. The constructor
    # form floatN(a, b, ...) is valid OpenCL C AND valid MSL with identical
    # semantics (single-arg splat is preserved by both spellings), so
    # rewrite the cast form everywhere, helpers and kernels alike.
    # A call-shaped 'f(float3)(...)' is left alone (the lookbehind only
    # fires the rewrite when '(' is not glued to an identifier or ')').
    body = re.sub(r"(?<![\w)])\((float[234]|int[234]|uint[234])\)\s*\(", r"\1(", body)
    return body


def rule_addr_space(body: str) -> str:
    # Order matters: two-word forms first
    for old, new in [
        ("__kernel void", "kernel void"),  # OpenCL kernel decls
        ("const __global ", "const device "),
        ("__global const ", "const device "),
        ("__global ", "device "),
        ("__local ", "threadgroup "),
        ("__constant ", "constant "),
        ("__private ", "thread "),
    ]:
        body = body.replace(old, new)
    return body


def rule_restrict(body: str) -> str:
    return body.replace(" restrict", "")


def _fn_spans(text: str):
    """Yield (name, header_start, body_open, body_close) for every
    'inline ... NAME(' / 'kernel void NAME(' function definition."""
    spans = []
    pat = re.compile(
        r"^(?:__attribute__\(\(noinline\)\)\s+)?(?:inline\s+)?[A-Za-z_][A-Za-z0-9_:<> \*&]*?\s\**([A-Za-z_][A-Za-z0-9_]*)\s*\(",
        re.M,
    )
    for m in pat.finditer(text):
        # signature close
        d = 0
        i = m.end() - 1
        while i < len(text):
            if text[i] == "(":
                d += 1
            elif text[i] == ")":
                d -= 1
                if d == 0:
                    break
            i += 1
        if i >= len(text):
            continue
        b_open = text.find("{", i)
        if b_open == -1 or text[i:b_open].count(";"):
            continue  # prototype, not a definition
        # match braces
        d = 0
        j = b_open
        while j < len(text):
            if text[j] == "{":
                d += 1
            elif text[j] == "}":
                d -= 1
                if d == 0:
                    break
            j += 1
        if j >= len(text):
            continue
        spans.append((m.group(1), m.start(), b_open, j))
    return spans


def _code_only(body: str) -> str:
    """Remove comments for dependency DETECTION only (the emitted text
    keeps them). Block comments and whole-line // comments are stripped;
    inline // after code is kept so string literals containing '//'
    cannot truncate real code."""
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    return re.sub(r"^[ \t]*//[^\n]*$", "", body, flags=re.M)


def propagate_gid(text: str) -> str:
    """Thread the work-item id through helper call graphs (see the
    gid propagation note in main()). Fixpoint over: functions whose
    body calls get_global_id(0), and functions that call any of
    those."""
    # functions that directly use the stub
    needs = set()
    fn_map = {}
    for (name, hs, bo, bc) in _fn_spans(text):
        fn_map[name] = (hs, bo, bc)
        if "get_global_id(0)" in _code_only(text[bo:bc]):
            needs.add(name)
    if not needs:
        return text
    # upward fixpoint: a function calling a needing function needs gid
    changed = True
    while changed:
        changed = False
        for name, (hs, bo, bc) in fn_map.items():
            if name in needs:
                continue
            body = _code_only(text[bo : bc + 1])
            for callee in needs:
                if callee == name:
                    continue
                if re.search(r"(?<![\w:.$])\b" + re.escape(callee) + r"\s*\(", body):
                    needs.add(name)
                    changed = True
                    break
    # kernels already declare 'const size_t gid = gid_;' - exclude them
    # from parameter injection (they are the roots)
    kernel_pat = re.compile(r"^kernel void\s+(\w+)\s*\(", re.M)
    kernel_names = set(kernel_pat.findall(text))

    # pass 1: inject 'thread const size_t& gid' into signatures of
    # non-kernel needing functions (last parameter). The signature
    # text starts at the header - scan FORWARD for its close paren.
    edits = []  # (position, old, new) - applied right-to-left
    for name in needs:
        if name in kernel_names or name == "get_global_id":
            continue
        hs, bo, bc = fn_map[name]
        # find signature open paren then its matching close
        po = text.find("(", hs)
        if po == -1 or po > bo:
            continue
        d = 0
        i = po
        while i < len(text):
            if text[i] == "(":
                d += 1
            elif text[i] == ")":
                d -= 1
                if d == 0:
                    break
            i += 1
        if i >= len(text) or i > bo:
            continue
        sig_close = i
        # comma decision must look at the last NON-whitespace char
        # before the close paren (the paren may be preceded by a
        # newline after an array-type parameter like 'float3 x[8]')
        k = sig_close - 1
        while k >= 0 and text[k].isspace():
            k -= 1
        if k < 0 or text[k] in "(,":
            inj = "thread const size_t& gid"
        else:
            inj = ", thread const size_t& gid"
        # Skip injection when the signature already has a gid parameter
        # (e.g. via SAMPLER_PARAM_DECL, which may already be expanded to
        # 'const size_t gid' at this stage). Injecting a second gid
        # parameter would collide.
        if "SAMPLER_PARAM_DECL" in text[hs:sig_close] or \
                re.search(r"\bgid\b", text[hs:sig_close]):
            continue
        edits.append((sig_close, "", inj))
    # pass 2: call sites of needing functions get ', gid' appended
    # before the matching close paren of the call. Definition headers
    # are skipped via FRESH spans - pass 1 has already shifted the
    # offsets captured in fn_map.
    fresh_spans = {name: (hs, bo, bc) for (name, hs, bo, bc) in _fn_spans(text)}
    for name in needs:
        if name == "get_global_id":
            continue
        for m in re.finditer(
            r"(?<![\w:.$])\b" + re.escape(name) + r"\s*\(", text
        ):
            cs = m.end() - 1
            d = 0
            i = cs
            while i < len(text):
                if text[i] == "(":
                    d += 1
                elif text[i] == ")":
                    d -= 1
                    if d == 0:
                        break
                i += 1
            if i >= len(text):
                continue
            call_close = i
            # skip call sites inside the function's own signature
            # (definition header) - those are covered by pass 1
            if name in fresh_spans:
                fhs, fbo, _ = fresh_spans[name]
                if fhs <= m.start() < fbo:
                    continue
            # does the call already pass gid as its last top-level
            # argument? (generated earlier pass, or through
            # SAMPLER_PARAM which expands to ", gid"). seg excludes
            # the closing paren, so scan backward at depth 0 for the
            # last argument instead of matching a trailing paren.
            seg = text[m.start() : call_close]
            if "SAMPLER_PARAM" in seg:
                continue
            depth = 0
            last_arg = ""
            call_open = cs - m.start()
            for ci in range(len(seg) - 1, -1, -1):
                ch = seg[ci]
                if ch == ")":
                    depth += 1
                elif ch == "(":
                    depth -= 1
                    if ci == call_open:
                        last_arg = seg[ci + 1:].strip()
                        break
                elif ch == "," and depth == 0:
                    last_arg = seg[ci + 1:].strip()
                    break
            if last_arg == "gid":
                continue
            inner = text[cs + 1 : call_close].rstrip()
            if not inner:
                edits.append((call_close, "", "gid"))
            else:
                edits.append((call_close, "", ", gid"))
    # apply edits right-to-left
    edits.sort(key=lambda t: -t[0])
    for pos, old, new in edits:
        text = text[:pos] + new + text[pos:]
    # finally: inside needing function BODIES, replace the stub call
    # with the now-parameterized gid. The local declaration line
    # 'const size_t gid = get_global_id(0);' must be REMOVED (it
    # would shadow the parameter and self-init). Re-derive spans from
    # the EDITED text - the pass-1/2 insertions above shifted every
    # offset captured in fn_map.
    spans2 = _fn_spans(text)
    for (name, hs2, bo2, bc2) in spans2:
        if name in kernel_names or name == "get_global_id":
            continue
        if name not in needs:
            continue
        body = text[bo2 : bc2 + 1]
        body2 = body.replace(
            "\tconst size_t gid = get_global_id(0);\n", ""
        ).replace("get_global_id(0)", "gid")
        if body2 != body:
            text = text[:bo2] + body2 + text[bc2 + 1 :]
    return text


def rule_struct_thread(body: str) -> str:
    """Whitelisted struct types: bare 'T *'/'T* name' in parameter or
    declaration position gets 'thread'. Splitting on candidate positions
    and checking the previous non-space char prevents matches inside
    expressions (e.g. multiplication)."""
    for ty in STRUCT_TYPES:
        # positions where 'Type *' can be a declaration: after '(' ',' ';'
        # '{' or at line start
        pattern = re.compile(
            r"([(,;{]\s*|^)((?:const\s+)?" + re.escape(ty) + r")(\s*\*)\s*(?=[A-Za-z_])",
            re.MULTILINE,
        )
        # guard: not already preceded by address-space keyword
        def repl(m):
            return m.group(1) + "thread " + m.group(2) + m.group(3) + " "

        body = pattern.sub(repl, body)
    return body


def rule_scalar_ptr_params(body: str) -> str:
    """Function definition lines: bare scalar pointers in the parameter
    list become 'thread' pointers. Signature spans are located from the
    opening '(' of a definition-looking line to its MATCHING ')' (which
    may be several lines away), so multi-line parameter lists are fully
    covered."""
    # find all signature starts: lines with 'name(' preceded by a
    # definition-ish prefix
    out = body
    # iterate over candidate openings
    pat = re.compile(r"^([^;\n()]*\b[A-Za-z_][A-Za-z0-9_]*\s*)\(", re.M)
    pos = 0
    pieces = []
    while pos < len(out):
        m = pat.search(out, pos)
        if not m:
            pieces.append(out[pos:])
            break
        start = m.end() - 1  # index of '('
        # walk to matching ')'
        depth = 0
        k = start
        while k < len(out):
            if out[k] == "(":
                depth += 1
            elif out[k] == ")":
                depth -= 1
                if depth == 0:
                    break
            k += 1
        if k >= len(out):
            pieces.append(out[pos:])
            break
        # only treat as signature if the closing paren is followed by
        # whitespace/{ on the same-ish position (a definition, not a call)
        after = out[k + 1 : k + 4].lstrip()
        if after.startswith("{") or after.startswith("\n"):
            span = out[start + 1 : k]
            span2 = re.sub(
                r"((?:^|,\s*)((?:const\s+)?(?:float|uint|int|bool|uchar|size_t|Spectrum)(?:\s*\*))\s*(?=[A-Za-z_]))",
                lambda mm: (mm.group(1)) + "thread " + (mm.group(2).rstrip()) + " ",
                span,
                flags=0,
            )
            # simpler: do the substitution on 'T *name' patterns
            span2 = re.sub(
                r"(,\s*|^\s*)((?:const\s+)?(?:float2|float3|float4|uint2|uint3|uint4|float|uint|int|bool|uchar|size_t|Spectrum|BSDFEvent|TextureType|UV|Ray|RayHit|Normal|Point|Vector|Seed|Frame|Material|LightSource|Triangle|Mesh|ExtMesh|Matrix4x4|Transform|Spectrum|ImageMap|GPUTask|GPUTaskState|SampleResult|EyePathInfo|PathVolumeInfo|MaterialEvalOp|InterpolatedTransform|Photon|RadiancePhoton|IndexBVHArrayNode|Distribution1D|EnvLightCache|PGIC|BCD|CUDADevice|OCLDevice|Texture|BSDF|HitPoint|HitPointInfo|Camera|Film|Filter|Sampler|RandomSampler|SobolSampler|TilePathSampler|MetropolisSampler)\s*\*)(\s*[A-Za-z_])",
                r"\1thread \2 \3",
                span,
                flags=re.M,
            )
            if span2 != span:
                pieces.append(out[pos : start + 1])
                pieces.append(span2)
                pos = k
                continue
        pieces.append(out[pos : k + 1])
        pos = k + 1
    return "".join(pieces)


def expand_macros(body: str, extra_defs: list = None, iterations: int = 10) -> str:
    """Expand the source's own parameter macros via cpp(1).

    The system preprocessor handles backslash continuations, nested
    macros and comments exactly like the OpenCL compiler did - no
    point reimplementing it. We keep #define lines out of the output
    (-P) and rely on the sources being self-contained for this pass.
    """
    import subprocess
    try:
        # always-present gate defines (the OpenCL build had them too)
        defines = ["-DLUXRAYS_OPENCL_DEVICE", "-DLUXRAYS_OPENCL_KERNEL",
                  "-DSLG_OPENCL_KERNEL"]
        for d in (extra_defs or []):
            d = d.strip()
            if not d:
                continue
            if d.startswith("-D"):
                d = d[2:].strip()
            if not d:
                continue
            defines.append("-D" + d)
        proc = subprocess.run(
            ["cpp", "-P", "-nostdinc", "-undef"] + defines,
            input=body,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if proc.returncode == 0 and proc.stdout:
            # drop the now-expanded #line artifacts (cpp -P has none)
            return proc.stdout
    except Exception:
        pass
    return body


def _rewrite_body_builtins(body: str) -> str:
    """Rewrite work-item/work-group builtin CALLS inside ONE kernel body
    onto the entry parameters injected by rule_kernel_buffer_attrs
    (gid_ is unconditional; lid_/lsize_/gridid_ are injected only when
    the body uses them). Helper functions are NOT passed through this -
    they keep the shim stubs (single-work-item semantics)."""
    body = re.sub(
        r"const\s+(?:size_t|int|uint|unsigned int)\s+gid\s*=\s*get_global_id\(0\);",
        "const size_t gid = gid_;",
        body,
    )
    # Bare reads (e.g. 'if (get_global_id(0) == 0)' in the film tonemap
    # reduce kernel): the stub always returned 0, making every thread
    # take the branch.
    body = body.replace("get_global_id(0)", "gid_")
    body = body.replace("get_local_id(0)", "lid_")
    body = body.replace("get_local_size(0)", "lsize_")
    body = body.replace("get_group_id(0)", "gridid_")
    return body


def _rewrite_kernel_bodies_only(text: str) -> str:
    """Apply _rewrite_body_builtins to the bodies of top-level kernels
    only (helper functions keep the shim stubs). Used by the no-scalar
    shortcut path, which does not walk kernel bodies itself."""
    out = []
    pos = 0
    pat = re.compile(r"^kernel void\s+\w+\s*\(", re.M)
    while pos < len(text):
        m = pat.search(text, pos)
        if not m:
            out.append(text[pos:])
            break
        s = m.end() - 1
        depth = 0
        k = s
        while k < len(text):
            if text[k] == "(":
                depth += 1
            elif text[k] == ")":
                depth -= 1
                if depth == 0:
                    break
            k += 1
        if k >= len(text):
            out.append(text[pos:])
            break
        b_open = text.find("{", k + 1)
        if b_open == -1:
            out.append(text[pos:])
            break
        d = 0
        j = b_open
        while j < len(text):
            if text[j] == "{":
                d += 1
            elif text[j] == "}":
                d -= 1
                if d == 0:
                    break
            j += 1
        if j >= len(text):
            out.append(text[pos:])
            break
        out.append(text[pos : b_open + 1])
        out.append(_rewrite_body_builtins(text[b_open + 1 : j]))
        out.append("}")
        pos = j + 1
    return "".join(out)


def rule_kernel_buffer_attrs(body: str) -> str:
    """Emit MSL resource bindings for kernel parameters: pointers get
    [[buffer(N)]], scalars are bundled per-kernel into a struct at
    buffer(0) (MSL allows max 31 buffer args). Also strips 'const' from
    scalar inputs and removes inline comments (they break macro
    expansion). After signature rewriting, rewrites each kernel BODY's
    references to its own bundled scalar names as scalars_->name.

    Also records the generated layouts in KERNEL_LAYOUTS (module-level)
    for the C++ header generator: {kernel_name: {scalars: [...],
    ptrs: [...]}}."""
    # Remove block comments body-wide first: their ')' and ',' would
    # corrupt signature paren matching and parameter splitting
    body = re.sub(r"/\*[^*]*(?:\*(?!/)[^*]*)*/", "", body)
    out = []
    kernel_scalar_structs = []
    kernel_ptr_structs = []
    kernel_infos = []  # (body_idx, [scalar names]) in output order
    kernel_names = []  # parallel to the structs: kernel name per index
    pos = 0
    pat = re.compile(r"^kernel void\s+(\w+)\s*\(", re.M)
    while pos < len(body):
        m = pat.search(body, pos)
        if not m:
            out.append(body[pos:])
            break
        start = m.end() - 1
        # Strip comments in the SIGNATURE REGION first: a ')' inside a
        # block comment would terminate the paren walk early. We don't
        # know the end yet, so strip comments from the kernel line
        # forward through a generous window and re-locate the paren
        # balance on the cleaned text. Simplest correct approach:
        # remove block comments from the whole body once (they cannot
        # affect code semantics elsewhere in MSL sources) before
        # scanning kernel signatures.
        # (done once per body at function entry - see below)
        start = m.end() - 1
        depth = 0
        k = start
        while k < len(body):
            if body[k] == "(":
                depth += 1
            elif body[k] == ")":
                depth -= 1
                if depth == 0:
                    break
            k += 1
        if k >= len(body):
            out.append(body[pos:])
            break
        out.append(body[pos : start + 1])
        sig = body[start + 1 : k]
        sig = re.sub(r"//[^\n]*", "", sig)
        # 2) split parameters on top-level commas
        params = []
        depth2 = 0
        cur = []
        for ch in sig:
            if ch == "(" or ch == "[":
                depth2 += 1
            elif ch == ")" or ch == "]":
                depth2 -= 1
            if ch == "," and depth2 == 0:
                params.append("".join(cur))
                cur = []
            else:
                cur.append(ch)
        params.append("".join(cur))

        new_params = []
        scalars = []
        scalar_names = []
        ptrs = []  # (type-head, name) bundled into buffer(1)
        for p in params:
            p2 = p.strip()
            if not p2:
                continue
            p2 = " ".join(p2.split())
            if "*" in p2:
                mm = re.match(r"^(.*\*+)\s*([A-Za-z_][A-Za-z0-9_]*)$", p2)
                if mm:
                    head = mm.group(1).strip()
                    # PRESERVE the address space from the original
                    # parameter (helpers expect matching qualifiers)
                    head2 = head
                    # 'const const' can appear from 'constant const'->rule
                    head2 = head2.replace("const const", "const")
                    name = mm.group(2)
                    ptrs.append((head2, name))
                    continue
                new_params.append(p2)
            else:
                # scalar: collect for the bundle (drop const)
                p2 = re.sub(r"^const\s+", "", p2)
                scalars.append(p2)
                nm = re.match(r"^[A-Za-z_][A-Za-z0-9_]*(?:\s+[A-Za-z_][A-Za-z0-9_]*)?\s+([A-Za-z_][A-Za-z0-9_]*)$", p2)
                if nm:
                    scalar_names.append(nm.group(1))
        # MSL kernel entry position parameter (work-item id)
        new_params.insert(0, "const uint gid_ [[thread_position_in_grid]]")
        if scalars:
            out_k = f"constant KernelScalars{len(kernel_scalar_structs)}* scalars_ [[buffer(0)]]"
            new_params.insert(1, out_k)
            kernel_scalar_structs.append(scalars)
            kernel_infos.append(scalar_names)
        else:
            kernel_infos.append([])
        # Kernel body span (from the kernel name to its closing brace):
        # used by the pointer-usage scan below AND by the work-group
        # builtin scan
        b_open = body.find("{", k + 1)
        b_close = body.find("\n}", k)
        kbody = body[k : b_close if b_close != -1 else len(body)]
        # Work-group builtins: inject the real MSL values only when the
        # kernel body uses them (the film tonemap reduce kernels)
        if "get_local_id(0)" in kbody:
            new_params.append("const uint lid_ [[thread_position_in_threadgroup]]")
        if "get_local_size(0)" in kbody:
            new_params.append("const uint lsize_ [[threads_per_threadgroup]]")
        if "get_group_id(0)" in kbody:
            new_params.append("const uint gridid_ [[threadgroup_position_in_grid]]")
        if ptrs:
            # Peek at the kernel body (from 'k' to its closing brace) to
            # find which pointers the body actually dereferences via
            # ptrs_->NAME. USED pointers bind DIRECTLY as kernel buffers
            # (verified on M5 Pro - gpuAddresses embedded in a constant
            # struct stop working past 16KB); UNUSED ones stay in the
            # struct bundle (NULL addresses are fine - never read).
            # NOTE: at this stage (first loop) bodies still reference the
            # pointers by their BARE names - the ptrs_-> prefix is added
            # by the symbol pass afterwards. Detect bare-name usage.
            used_names = set()
            for _h, _n in ptrs:
                if re.search(r"(?<![\w:.$])\b" + re.escape(_n) + r"\b", kbody):
                    used_names.add(_n)
            direct_ptrs = [(h, n) for (h, n) in ptrs if n in used_names]
            struct_ptrs = [(h, n) for (h, n) in ptrs if n not in used_names]
            # Buffer slots are limited to 31: direct-bind used pointers
            # only while slots remain; the rest go into the struct
            # (unused/unread ones are safe as NULL gpuAddresses; the
            # overflow USED ones will need engine-side argument tables)
            next_idx = 2  # buffer(0)=scalars, 1=struct bundle
            overflow = []
            for head, name in direct_ptrs:
                if next_idx > 30:
                    overflow.append((head, name))
                    continue
                head2 = head.replace("const const", "const").strip()
                new_params.append(f"{head2} {name} [[buffer({next_idx})]]")
                next_idx += 1
            final_struct = struct_ptrs + overflow
            # Stash the exact direct/table split the signature uses
            # (direct = used pointers that got a slot; table = unused +
            # overflow). The KERNEL_LAYOUTS record below (which runs
            # later) copies these - the host marshalling must match the
            # signature or dispatches abort past buffer(30).
            _split_direct[m.group(1)] = [
                (h, n) for (h, n) in direct_ptrs
                if (h, n) not in overflow
            ]
            _split_table[m.group(1)] = list(final_struct)
            if final_struct:
                # device (not constant) address space: on Apple GPUs,
                # dereferencing gpuAddress values stored in a CONSTANT
                # struct returns 0 (verified on M5 Pro via probe kernel);
                # the same table bound as device memory works. Scalars
                # (plain values, no double indirection) stay constant.
                out_p = f"const device KernelPtrs{len(kernel_scalar_structs)-1}* ptrs_ [[buffer(1)]]"
                new_params.insert(2, out_p)
                kernel_ptr_structs.append(final_struct)
            else:
                kernel_ptr_structs.append([])
        # record kernel name aligned to the struct index just appended
        kernel_names.append(m.group(1))
        # Full engine-argument order: walk the original signature params
        # and emit one entry per arg - ("s", scalar_name) or ("p", ptr
        # name). The host-side marshalling consumes engine SetKernelArg
        # calls in THIS order; the separate direct/table lists alone
        # would reorder pointers (direct-then-table) and misalign every
        # kernel whose signature interleaves the two.
        arg_order = []
        for p in params:
            p2 = " ".join(p.strip().split())
            if not p2:
                continue
            if "*" in p2:
                mm2 = re.match(r"^(.*\*+)\s*([A-Za-z_][A-Za-z0-9_]*)$", p2)
                if mm2:
                    arg_order.append(["p", mm2.group(2)])
            else:
                nm2 = re.match(r"^[A-Za-z_][A-Za-z0-9_]*(?:\s+[A-Za-z_][A-Za-z0-9_]*)?\s+([A-Za-z_][A-Za-z0-9_]*)$", p2)
                if nm2:
                    arg_order.append(["s", nm2.group(1)])
        KERNEL_LAYOUTS[m.group(1)] = {
            "scalar_fields": list(scalars),
            "ptr_fields": [(h, n) for (h, n) in ptrs],
            "arg_order": arg_order,
            "direct_fields": _split_direct.get(m.group(1), []),
            "table_fields": _split_table.get(m.group(1), []),
        }
        out.append(", ".join(new_params))
        pos = k
    if not kernel_scalar_structs:
        # No kernel had scalar args (no KernelScalarsN bundles) - the
        # full symbol pass below has nothing to do, but the work-item id
        # rewrite MUST still run (kernels with only pointer args still
        # declare 'const size_t gid = get_global_id(0);' and the shim
        # stub always returns 0).
        out_joined = "".join(out)
        out_joined = _rewrite_kernel_bodies_only(out_joined)
        return out_joined

    # ---- symbol-table pass over kernel bodies ----
    # Each kernel signature references its own KernelScalarsN struct.
    # Parse the struct field names first, then in each kernel body,
    # prefix references to that kernel's own scalars with scalars_->.
    # Field names per struct index, derived from the collected data
    # (the struct text is only generated at return time - parsing
    # 'out' would always find nothing)
    struct_fields = {}
    for idx, sc in enumerate(kernel_scalar_structs):
        fields = []
        for s in sc:
            fm = re.match(r"^[A-Za-z_][A-Za-z0-9_]*(?:\s+[A-Za-z_][A-Za-z0-9_]*)?\s+([A-Za-z_][A-Za-z0-9_]*)$", s.strip())
            if fm:
                fields.append(fm.group(1))
        struct_fields[idx] = fields
    ptr_fields = {}
    for idx, pt in enumerate(kernel_ptr_structs):
        ptr_fields[idx] = [name for (_head, name) in pt]

    joined = "".join(out)
    out2 = []
    pos2 = 0
    kpat = re.compile(r"^kernel void\s+(\w+)\s*\(", re.M)
    while pos2 < len(joined):
        m2 = kpat.search(joined, pos2)
        if not m2:
            out2.append(joined[pos2:])
            break
        # find signature closing paren
        s2 = m2.end() - 1
        d2 = 0
        e2 = s2
        while e2 < len(joined):
            if joined[e2] == "(":
                d2 += 1
            elif joined[e2] == ")":
                d2 -= 1
                if d2 == 0:
                    break
            e2 += 1
        if e2 >= len(joined):
            out2.append(joined[pos2:])
            break
        sig_text = joined[m2.start() : e2 + 1]
        # which struct does this kernel use?
        sm = re.search(r"KernelScalars(\d+)", sig_text)
        names = struct_fields.get(int(sm.group(1)), []) if sm else []
        pnames = ptr_fields.get(int(sm.group(1)), []) if sm else []
        # direct-bound pointers: no ptrs_-> prefix (they are real params)
        if "ptrs_" not in sig_text:
            pnames = []
        # copy signature as-is
        out2.append(joined[pos2 : e2 + 1])
        # body span: the kernel's OWN body - from its opening '{' to the
        # matching closing '}' (helpers after it are NOT touched)
        b_open = joined.find("{", e2 + 1)
        if b_open == -1:
            out2.append(joined[e2 + 1 :])
            pos2 = len(joined)
            continue
        d3 = 0
        k3 = b_open
        while k3 < len(joined):
            if joined[k3] == "{":
                d3 += 1
            elif joined[k3] == "}":
                d3 -= 1
                if d3 == 0:
                    break
            k3 += 1
        body_end = k3 + 1 if k3 < len(joined) else len(joined)
        body = joined[e2 + 1 : body_end]
        for nm in set(names):
            body = re.sub(
                r"(?<![\w:.$])\b" + re.escape(nm) + r"\b",
                "scalars_->" + nm,
                body,
            )
            body = body.replace("scalars_->scalars_->", "scalars_->")
        for nm in set(pnames):
            body = re.sub(
                r"(?<![\w:.$])\b" + re.escape(nm) + r"\b",
                "ptrs_->" + nm,
                body,
            )
            body = body.replace("ptrs_->ptrs_->", "ptrs_->")
        # Work-item id: kernels receive gid_ as a signature parameter;
        # helper functions keep the shim's get_global_id() stub.
        # Match every declaration variant (size_t/int/uint) - the RT
        # kernel (Accelerator_Intersect_RayBuffer) declares
        # 'const int gid = ...' and a literal-only pattern missed it,
        # leaving the stub (always 0) in place: only task 0 got traced.
        # Work-group builtins (film tonemap reduce kernels) are handled
        # in the same pass via the injected lid_/lsize_/gridid_ params.
        body = _rewrite_body_builtins(body)
        out2.append(body)
        pos2 = body_end
    joined = "".join(out2)

    # ---- gid propagation pass ----
    # OpenCL semantics: get_global_id(0) inside a helper returns the
    # CALLING work-item's id. The MSL shim can't reproduce that (no
    # TLS in kernels), so propagate the kernel's 'gid' down the call
    # graph: every helper that uses get_global_id(0) (directly, or via
    # a helper that does) gains a 'thread const size_t& gid' last
    # parameter, call sites pass 'gid', and the kernel root already
    # has its local. Fixpoint because the fan-in spreads upward.
    joined = propagate_gid(joined)

    # emit struct definitions just before the FIRST kernel
    # declaration (after all type definitions in the stream)
    header = "\n// ==== generated kernel scalar bundles ====\n"
    for i, sc in enumerate(kernel_scalar_structs):
        header += f"struct KernelScalars{i} {{\n"
        seen = set()
        for s in sc:
            mm = re.match(r"^([A-Za-z_][A-Za-z0-9_]*(?:\s+[A-Za-z_][A-Za-z0-9_]*)?)\s+([A-Za-z_][A-Za-z0-9_]*)$", s)
            if mm and mm.group(2) not in seen:
                seen.add(mm.group(2))
                header += f"  {mm.group(1)} {mm.group(2)};\n"
        header += "};\n"
    header += "// ==== generated kernel pointer bundles ====\n"
    for i, pt in enumerate(kernel_ptr_structs):
        header += f"struct KernelPtrs{i} {{\n"
        for head, name in pt:
            if head.startswith("device") or head.startswith("constant") or head.startswith("threadgroup") or head.startswith("thread"):
                header += f"  {head} {name};\n"
            else:
                header += f"  device {head} {name};\n"
        header += "};\n"

    # find the first kernel declaration; ensure it is top-level by
    # checking brace balance of the text before it is zero
    for m in re.finditer(r"^kernel void\s", joined, re.M):
        before = joined[: m.start()]
        bal = before.count("{") - before.count("}")
        if bal == 0:
            return joined[: m.start()] + header + joined[m.start():]
    # fallback: append at the end
    return joined + header


def rule_kernel_scalar_const(body: str) -> str:
    """MSL kernel input declarations may not carry 'const' (and pointer
    args get address spaces elsewhere). Inside kernel signature spans,
    strip 'const' from non-pointer parameter declarations."""
    out = []
    pos = 0
    pat = re.compile(r"^kernel void\s+\w+\s*\(", re.M)
    while pos < len(body):
        m = pat.search(body, pos)
        if not m:
            out.append(body[pos:])
            break
        start = m.end() - 1
        depth = 0
        k = start
        while k < len(body):
            if body[k] == "(":
                depth += 1
            elif body[k] == ")":
                depth -= 1
                if depth == 0:
                    break
            k += 1
        if k >= len(body):
            out.append(body[pos:])
            break
        out.append(body[pos : start + 1])
        sig = body[start + 1 : k]
        # inline comments swallow the macro continuation when a
        # multi-line macro is expanded here - strip them in signatures
        sig = re.sub(r"//[^\n]*", "", sig)
        # strip 'const' only when followed by a scalar type (not pointer)
        sig = re.sub(r"\bconst\s+((?:float|uint|int|bool|uchar|size_t|float2|float3|float4|uint2|uint3|uint4)(?:\s+[A-Za-z_][A-Za-z0-9_]*\s*(?:=|,|\)|\n)))",
                     r"\1", sig)
        out.append(sig)
        pos = k
    return "".join(out)



def translate(cl_source: str, params: list) -> str:
    """Apply the full proven rule chain to an engine-assembled .cl
    source. params are the engine's -D options (RenderEngine type,
    epsilons, BVH pages...); they become cpp defines for macro
    expansion (matching what the OpenCL runtime did)."""
    # ---- input side: emulate the FILES loop over ONE combined source ----
    body = clean_lines(cl_source)
    body = rule_vector_compound_literal(body)
    body = rule_addr_space(body)
    body = rule_restrict(body)
    body = rule_struct_thread(body)
    body = rule_scalar_ptr_params(body)
    parts = [SHIM, "\n// ==== engine program ====\n", body]

    # GLOBAL passes on the fully assembled source (same order as the
    # proven pipeline): macro expansion, post-expansion bare-pointer
    # rule, shim re-add, BVH struct access, kernel signature/buffer
    # binding, scalar const strip, cleanup, noinline VM cut.
    assembled = "".join(parts)
    assembled = expand_macros(assembled, params)
    # Re-run the bare-pointer param rule post-expansion: cpp replaces
    # OPENCL_FORCE_INLINE with 'inline', changing line shapes, and the
    # gate defines (-DSLG_OPENCL_KERNEL etc.) reveal definitions that
    # the file-local pass never saw.
    assembled = rule_scalar_ptr_params(assembled)
    # cpp(-P) removes ALL #define lines including the shim's own
    # (MAKE_FLOAT3, math macros, engine gate defines). Re-prepend the
    # shim so these macros exist again in the final source; the
    # definition lines are harmless duplicates of what cpp consumed.
    # Skip the re-add if cpp failed and returned the input unchanged.
    if "#define MAKE_FLOAT3" not in assembled:
        # Re-add ONLY the macro definition lines from the shim: cpp kept
        # the inline functions (they are not macros) but consumed the
        # #defines, so re-adding functions would duplicate them.
        # Only the non-math macros cpp couldn't have already expanded
        # into bodies (math macros DID expand with metal:: prefix
        # applied by cpp itself - wait: cpp doesn't know metal::, it
        # expands them literally, leaving 'metal::log(x)' in the text;
        # re-adding those macros would double-expand on the Metal side.
        # So re-add ONLY: MAKE_FLOAT*, engine gates, and atomics which
        # cpp left as plain identifiers (no metal:: prefix).
        keep = []
        for l in SHIM.splitlines():
            if not l.startswith("#define"):
                continue
            name = l.split()[1].split("(")[0]
            # skip math macros (they contain 'metal::' in their body)
            if "metal::" in l:
                continue
            keep.append(l)
        assembled = "\n".join(keep) + "\n" + assembled
    # ---- BVH float4-view fix ----
    # bvh.cl reads node fields through a 'float4*' reinterpret of the
    # BVHArrayNode pointer (data0/data1, then as_uint(data1.z) etc).
    # In MSL that aliasing cast misbehaves on Apple GPUs: the loads
    # past the union return 0 (measured: nodeData read as 0 while the
    # struct-field access reads 10). Replace the whole trick with
    # direct struct field access - the field layout is identical
    # (bboxMin[3]+bboxMax[3] / v[3]+meshIndex+triangleIndex union,
    # nodeData@24), so the packed bytes are unchanged.
    def rule_bvh_struct_access(t: str) -> str:
        # the traversal reads inside Accelerator_Intersect
        t = t.replace(
            "\t\t// Read the node\n"
            "\t\tdevice float4* data = (device float4*)node;\n"
            "\t\tconst float4 data0 = *data++;\n"
            "\t\tconst float4 data1 = *data;\n",
            "\t\t// Read the node (struct-field access: MSL's float4-view\n"
            "\t\t// reinterpret returns 0 past the union on Apple GPUs)\n",
        )
        # fallback regex in case spacing differs
        t = re.sub(
            r"//\s*Read the node\n\s*device float4\* data = \(device float4\*\)node;\n\s*const float4 data0 = \*data\+\+;\n\s*const float4 data1 = \*data;\n",
            "// Read the node (struct-field access: MSL float4-view returns 0 on Apple GPUs)\n",
            t,
        )
        t = t.replace("const uint nodeData = as_uint(data1.z);",
                      "const uint nodeData = node->nodeData;")
        t = t.replace("const uint v0 = as_uint(data0.x);",
                      "const uint v0 = node->triangleLeaf.v[0];")
        t = t.replace("const uint v1 = as_uint(data0.y);",
                      "const uint v1 = node->triangleLeaf.v[1];")
        t = t.replace("const uint v2 = as_uint(data0.z);",
                      "const uint v2 = node->triangleLeaf.v[2];")
        t = t.replace("const uint meshIndex = as_uint(data0.w);",
                      "const uint meshIndex = node->triangleLeaf.meshIndex;")
        t = t.replace("const uint triangleIndex = as_uint(data1.x);",
                      "const uint triangleIndex = node->triangleLeaf.triangleIndex;")
        # cpp already expanded MAKE_FLOAT3 into (float3(...)); match both forms
        # cpp-expanded form: (float3(data0.x,  data0.y,  data0.z)) - note the
        # unclosed 'float3(' style; match any 'float3'-ish opener
        t = re.sub(
            r"const float3 pMin = \(\s*(?:metal::)?float3\s*\(\s*data0\.x,\s*data0\.y,\s*data0\.z\s*\)\s*\);",
            "const float3 pMin = (float3(node->bvhNode.bboxMin[0], node->bvhNode.bboxMin[1], node->bvhNode.bboxMin[2]));",
            t)
        t = re.sub(
            r"const float3 pMax = \(\s*(?:metal::)?float3\s*\(\s*data0\.w,\s*data1\.x,\s*data1\.y\s*\)\s*\);",
            "const float3 pMax = (float3(node->bvhNode.bboxMax[0], node->bvhNode.bboxMax[1], node->bvhNode.bboxMax[2]));",
            t)
        # anything still referencing the float4 views in the BVH walk
        # (leaf vertex fetches have slightly different spacing after cpp)
        t = t.replace("const uint v0 = as_uint(data0.x);",
                      "const uint v0 = node->triangleLeaf.v[0];")
        t = t.replace("const uint v1 = as_uint(data0.y);",
                      "const uint v1 = node->triangleLeaf.v[1];")
        t = t.replace("const uint v2 = as_uint(data0.z);",
                      "const uint v2 = node->triangleLeaf.v[2];")
        t = t.replace("const uint meshIndex = as_uint(data0.w);",
                      "const uint meshIndex = node->triangleLeaf.meshIndex;")
        t = t.replace("const uint triangleIndex = as_uint(data1.x);",
                      "const uint triangleIndex = node->triangleLeaf.triangleIndex;")
        # MBVH leaf fields (mbvh.cl): as_int() reads and a meshIndex variant
        # carrying the mesh offset suffix
        t = t.replace("const uint meshIndex = as_uint(data0.w) + currentMeshOffset;",
                      "const uint meshIndex = node->triangleLeaf.meshIndex + currentMeshOffset;")
        t = t.replace("const uint transformIndex = as_int(data0.y);",
                      "const uint transformIndex = node->bvhLeaf.transformIndex;")
        t = t.replace("const uint motionIndex = as_int(data0.z);",
                      "const uint motionIndex = node->bvhLeaf.motionIndex;")
        t = t.replace("currentMeshOffset = as_int(data0.w);",
                      "currentMeshOffset = node->bvhLeaf.meshOffsetIndex;")
        t = t.replace("const uint leafIndex = as_int(data0.x);",
                      "const uint leafIndex = node->bvhLeaf.leafIndex;")
        # mbvh.cl declares the float4 view through a const device pointer
        t = re.sub(
            r"//\s*Read the node\n\s*const device float4\* data = \(const device float4\*\)node;\n\s*const float4 data0 = \*data\+\+;\n\s*const float4 data1 = \*data;\n",
            "// Read the node (struct-field access: MSL float4-view returns 0 on Apple GPUs)\n",
            t,
        )
        return t

    assembled = rule_bvh_struct_access(assembled)
    assembled = rule_kernel_buffer_attrs(assembled)
    assembled = rule_kernel_scalar_const(assembled)

    # ---- final cleanup passes (session-5 error catalog) ----
    # MSL attribute keyword collisions: 'vertex' as a parameter name
    assembled = re.sub(r"\bvertex\b", "vertex_", assembled)

    # gid propagation safety net: every helper that used the
    # get_global_id(0) stub now receives 'gid' as a parameter; the
    # local declaration line inside those bodies must go (it would
    # shadow the parameter). The declaration has one unique shape.
    # A body whose decl line was rewritten to 'gid' by the stub
    # replacement BEFORE removal shows up as a self-init - the
    # parameter already carries the value, so drop the line too.
    assembled = assembled.replace(
        "\tconst size_t gid = get_global_id(0);\n", ""
    )
    assembled = assembled.replace("\tconst size_t gid = gid;\n", "")

    # Macro invocations with a space before '(' (e.g. 'MAKE_FLOAT3 (')
    assembled = re.sub(r"\b(MAKE_FLOAT[234])\s+\(", r"\1(", assembled)
    # Body-local pointer declarations initialized from an address:
    # 'T *name = &...' are OpenCL private (thread) pointers
    assembled = re.sub(
        r"^(\s*)((?:const\s+)?(?:[A-Za-z_][A-Za-z0-9_]*)(?:\s+\*+\s*|\*+\s*))([A-Za-z_][A-Za-z0-9_]*\s*=\s*&)",
        r"\1thread \2\3",
        assembled,
        flags=re.M,
    )

    # ---- inline-graph cut for the eval VMs ----
    # The material/texture evaluation VM interpreters (EvalOp dispatchers
    # and the per-type Evaluate functions they call) are the single largest
    # inline graph in the engine: Scene_Intersect -> BSDF_Init ->
    # Material_Bump -> Material_EvalOp -> 30+ per-material Evaluate ->
    # Texture_EvalOp -> 50+ per-texture Evaluate. One micro-kernel that
    # pulls all of that (AdvancePaths_MK_RT_NEXT_VERTEX) makes the Metal
    # BACKEND compiler run 10+ minutes at 100% CPU and then die with
    # XPC_ERROR_CONNECTION_INTERRUPTED (MTLCompilerService crash).
    # Cutting the graph at the VM boundaries keeps each function a
    # manageable call target. Register pressure also drops, which helps
    # occupancy. MSL supports __attribute__((noinline)) on functions.
    # Order matters: check longest signatures first.
    _noinline_suffixes = [
        # VM dispatchers ('<Type>Material_EvalOp(' / 'Texture_EvalOp(')
        "Material_EvalOp",
        "Texture_EvalOp",
        # per-material evaluate bodies (called from the dispatchers)
        "Material_Evaluate",
        "Material_EvaluatePre",
        "Material_GetInteriorVolume",
        "Material_GetExteriorVolume",
        # per-texture evaluate bodies (called from Texture_EvalOp)
        "Texture_Evaluate",
        # volume scatter drags the texture VM through ior/density evals
        "Volume_Scatter",
        # hit-point setup evaluates UV/alpha textures
        "Material_Bump",
        "HitPoint_Init",
        # slow-path texture reads (image maps, buffer indirection)
        "Texture_GetFloatValueSlowPath",
        "Texture_GetSpectrumValueSlowPath",
    ]
    # Only annotate DEFINITIONS: they start a line with 'inline'; call
    # sites are indented. Suffix match catches both the generic entry
    # ('Material_Evaluate(') and the per-type variants
    # ('ArchGlassMaterial_Evaluate(').
    for fn in _noinline_suffixes:
        assembled = re.sub(
            r"^inline ([A-Za-z_][A-Za-z0-9_:<> \*&]*?)([A-Za-z0-9_]*" + re.escape(fn) + r")\(",
            r"__attribute__((noinline)) inline \1\2(",
            assembled,
            flags=re.M,
        )

    # ---- layout probe kernels ----
    # One probe per scalar bundle: writes [sizeof, field offsets...] to
    # a buffer, so the host reads Metal's OWN layout for the bundles it
    # must fill. (The rewriter emits the struct fields; the Metal
    # compiler decides padding - the C++ side must not guess.)
    # NOTE: offsetof on constant-addressed struct fields is not
    # expressible in pure MSL; instead the probe is emitted with
    # __builtin_offsetof equivalents where possible. MSL supports
    # __builtin_offsetof(T, field)! Use it.
    probe2 = "\n// ==== layout probes (generated) ====\n"
    for kname, layout in KERNEL_LAYOUTS.items():
        if not layout["scalar_fields"]:
            continue
        idx = None
        for e in re.finditer(r"kernel void " + re.escape(kname) + r"\(", assembled):
            m2 = re.search(r"KernelScalars(\d+)", assembled[e.start():e.start()+400])
            if m2:
                idx = m2.group(1)
                break
        if idx is None:
            continue
        probe2 += (
            "kernel void _LayoutProbe_" + kname + "("
            "device uint* out [[buffer(0)]]) {\n"
            "if (get_global_id(0) != 0u) return;\n"
            "uint o = 0;\n"
            "out[o++] = (uint)sizeof(KernelScalars" + idx + ");\n"
        )
        seen = set()
        for s in layout["scalar_fields"]:
            mm = re.match(r"^([A-Za-z_][A-Za-z0-9_]*(?:\s+[A-Za-z_][A-Za-z0-9_]*)?)\s+([A-Za-z_][A-Za-z0-9_]*)$", s.strip())
            if not mm:
                continue
            fname = mm.group(2)
            if fname in seen:
                continue
            seen.add(fname)
            probe2 += ("out[o++] = (uint)__builtin_offsetof(KernelScalars"
                       + idx + ", " + fname + ");\n")
        probe2 += "}\n"
    assembled = assembled + probe2

    return assembled


def main():
    if len(sys.argv) < 3:
        print("usage: cl2msl.py <outMSL> <outJSON> [-D ...|-D...] < <source.cl>",
              file=sys.stderr)
        return 1
    out_msl = Path(sys.argv[1])
    out_json = Path(sys.argv[2])
    params = sys.argv[3:]   # may be empty (no -D options)

    cl_source = sys.stdin.read()

    msl = translate(cl_source, params)
    out_msl.write_text(msl)

    # ---- argument marshalling map for MetalDevice ----
    # scalar type mapping for C++ fixed-width mirroring
    def cpp_sizeof(msl_type: str) -> int:
        t = msl_type.strip()
        sizes = {
            "float": 4, "uint": 4, "int": 4, "bool": 1, "uchar": 1,
            "size_t": 8, "float2": 8, "float3": 12, "float4": 16,
            "uint2": 8, "uint3": 12, "uint4": 16,
        }
        return sizes.get(t, 0)  # 0 = opaque engine struct

    layouts = {}
    for kname, layout in KERNEL_LAYOUTS.items():
        scalars = []
        for s in layout["scalar_fields"]:
            mm = re.match(r"^([A-Za-z_][A-Za-z0-9_]*(?:\s+[A-Za-z_][A-Za-z0-9_]*)?)\s+([A-Za-z_][A-Za-z0-9_]*)$", s.strip())
            if mm:
                scalars.append([mm.group(2), mm.group(1), cpp_sizeof(mm.group(1))])
        # direct vs table split: same decision the rewriter made when
        # emitting the signature - a pointer binds DIRECT when the
        # kernel body references its bare name AND slots remain
        # (buffer(2..30)); everything else rides the KernelPtrsN table.
        direct = [[name, head] for (head, name) in layout.get("direct_fields", [])]
        table = [[name, head] for (head, name) in layout.get("table_fields", [])]
        layouts[kname] = {
            "scalars": scalars,
            "direct": direct,
            "table": table,
            # Original-signature argument order as ["s"|"p", name] pairs:
            # the engine sets kernel args in THIS order, so the host
            # marshalling walks this list - not the reordered direct+
            # table concatenation.
            "order": layout.get("arg_order", []),
        }
    out_json.write_text(json.dumps(layouts, indent=1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
