# SPDX-FileCopyrightText: 2024-2025 Authors (see AUTHORS.txt)
#
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "pysuperluxcore"
dynamic = ["version"]
dependencies = [
  "nvidia-cuda-nvrtc-cu12 == 12.8.93; sys_platform != 'darwin' and platform_machine != 'ARM64'",
]
requires-python = ">= 3.10"
description = "LuxCore Python bindings"
authors = [{name="LuxCoreRender"}]
## See https://pypi.org/classifiers/
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Development Status :: 7 - Inactive",
    "Topic :: Multimedia :: Graphics :: 3D Rendering",
]
readme = "README.md"
keywords = [
  "raytracing",
  "ray tracing",
  "rendering",
  "pbr",
  "physical based rendering",
  "path tracing",
]

[project.urls]
Homepage = "https://luxcorerender.org/"
Documentation = "http://wiki.luxcorerender.org/LuxCoreRender_Wiki"
GitHub = "https://github.com/claudianus/SuperLuxCore"

[project.scripts]
pysuperluxcoretest = "pysuperluxcoretest:main"
pysuperluxcore-console = "pysuperluxcoretools.console.cmd:main"
pysuperluxcore-maketx = "pysuperluxcoretools.maketx.cmd:main"
pysuperluxcore-merge = "pysuperluxcoretools.merge.cmd:main"
pysuperluxcore-netmenu = "pysuperluxcoretools.netmenu.cmd:main"
pysuperluxcore-netconsole = "pysuperluxcoretools.netconsole.cmd:main"
pysuperluxcore-netnode = "pysuperluxcoretools.netnode.cmd:main"

[project.gui-scripts]
pysuperluxcore-netconsole-ui = "pysuperluxcoretools.netconsole.ui:main"
pysuperluxcore-netnode-ui = "pysuperluxcoretools.netnode.ui:main"

[tool.scikit-build]
logging.level = "DEBUG"
build.verbose = true
cmake.source-dir = "."
build.targets = ["pysuperluxcore"]
wheel.cmake = true
wheel.packages = ["python/pysuperluxcore", "python/pysuperluxcoretest", "python/pysuperluxcoretools"]
build-dir = "out"
ninja.make-fallback = false
install.components = ["pysuperluxcore"]
experimental = true

[tool.scikit-build.cmake.define]
CMAKE_INSTALL_PREFIX = "install"
#CMAKE_TOOLCHAIN_FILE = "out/build/Release/conan_toolchain.cmake"

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
regex = "(?P<version>.*)"
input = "SKVERSION"
result = "{version}"

[tool.black]
line-length = 79
