# SPDX-License-Identifier: Apache-2.0
#
# Generates the measured-media SSS preset table for OpenPBR's
# "subsurfacepreset" property (parsematerials.cpp) and the matching
# adapter-side seed table (SuperBlendLuxCore openpbr node).
#
# Source data: measured (sigma_a, sigma_s') in mm^-1 at RGB primaries
# (~650/550/450 nm) from
#   Jensen, Marschner, Levoy, Hanrahan, "A Practical Model for
#     Subsurface Light Transport", SIGGRAPH 2001 (Table III)
#   Narasimhan et al., "Acquiring Scattering Properties of
#     Participating Media by Dilution", SIGGRAPH 2006
# (values as tabulated in PBRT-v3 src/core/medium.cpp).
#
# Conversion to the engine's albedo parametrization (per channel):
#   sigma_t' = sigma_a + sigma_s'      (reduced extinction)
#   alpha'   = sigma_s' / sigma_t'     (reduced single-scatter albedo)
#   d        = 1 / sigma_t'            (transport mean free path)
#   A        = R_vdH(alpha') * K(alpha', eta_medium)
# where R_vdH inverts SSSAlphaVanDeHulst (d'Eon Hitchhiker's Eq. 53.7)
# numerically and K = Rd_cb15(eta)/Rd_cb15(1) is the internal-Fresnel
# trapping ratio the engine applies at render time - baking it into A
# at the medium's canonical IOR makes the preset reproduce the measured
# apparent reflectance when specular IOR matches the medium's physical
# value. The per-channel d vector is normalized to its max channel so
# it maps onto subsurfaceradiusscale, with d_max becoming the suggested
# subsurfaceradius (meters, i.e. scene units).
#
# Usage: python3 dev-tools/gen_sss_presets.py

import math

# name -> (sigma_a RGB, sigma_s' RGB mm^-1, canonical interior IOR, source)
MEASURED = {
    "skin_dark":   ((0.032, 0.17, 0.48),   (0.74, 0.88, 1.01), 1.4,  "Jensen'01 Skin1"),
    "skin_light":  ((0.013, 0.070, 0.145), (1.09, 1.59, 1.79), 1.4,  "Jensen'01 Skin2"),
    "chicken":     ((0.015, 0.077, 0.19),  (0.15, 0.21, 0.38), 1.4,  "Jensen'01 Chicken1"),
    "apple":       ((0.0030, 0.0034, 0.046), (2.29, 2.39, 1.97), 1.35, "Jensen'01 Apple"),
    "potato":      ((0.0024, 0.0090, 0.12), (0.68, 0.70, 0.55), 1.35, "Jensen'01 Potato"),
    "marble":      ((0.0021, 0.0041, 0.0071), (2.19, 2.62, 3.00), 1.5, "Jensen'01 Marble"),
    "cream":       ((0.0002, 0.0028, 0.0163), (7.38, 5.47, 3.15), 1.35, "Jensen'01 Cream"),
    "whole_milk":  ((0.0011, 0.0024, 0.014), (2.55, 3.21, 3.77), 1.35, "Jensen'01 Wholemilk"),
    "skim_milk":   ((0.0014, 0.0025, 0.0142), (0.70, 1.22, 1.90), 1.35, "Jensen'01 Skimmilk"),
    "ketchup":     ((0.061, 0.97, 1.45),   (0.18, 0.07, 0.03),  1.35, "Jensen'01 Ketchup"),
}


def clamp(x, lo, hi):
    return min(max(x, lo), hi)


# Mirrors SSSAlphaVanDeHulst() in src/slg/volumes/homogenous.cpp (g=0).
def vdh_alpha(A, g=0.0):
    x = 4.20863 * A + 4.09712 - math.sqrt(
        9.59217 + 41.6808 * A + 17.7126 * A * A)
    s2 = x * x
    return clamp((1.0 - s2) / (1.0 - g * s2), 0.0, 0.999999)


# Inverse of vdh_alpha(A, 0): matched-boundary reflectance R such that
# the vdH remap of A=R yields single-scatter albedo alpha.
def vdh_reflectance(alpha):
    lo, hi = 0.0, 0.999
    for _ in range(60):
        mid = 0.5 * (lo + hi)
        if vdh_alpha(mid) < alpha:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


# Mirrors SSSRdDiffusion() in src/slg/volumes/homogenous.cpp.
def rd_diffusion(a, eta):
    e = max(eta, 1.0001)
    rho_e = -1.4399 / (e * e) + 0.7099 / e + 0.6681 + 0.0636 * e
    ab = (1.0 + rho_e) / max(1.0 - rho_e, 1e-4)
    return 0.5 * a * (1.0 + math.exp(-4.0 / 3.0 * ab * math.sqrt(3.0 * (1.0 - a))))


def convert(sigma_a, sigma_sp, eta):
    albedo, mfp = [], []
    for c in range(3):
        st = sigma_a[c] + sigma_sp[c]
        alpha = sigma_sp[c] / st
        k = rd_diffusion(alpha, eta) / rd_diffusion(alpha, 1.0)
        albedo.append(clamp(vdh_reflectance(alpha) * k, 0.0, 0.999))
        mfp.append(1.0 / st * 1e-3)  # mm^-1 -> m
    dmax = max(mfp)
    scale = [d / dmax for d in mfp]
    return albedo, scale, dmax


def fmt3(v):
    return "{%s}" % ", ".join(f"{x:.6g}f" for x in v)


def main():
    print("// --- generated by dev-tools/gen_sss_presets.py ---")
    for name, (sa, ssp, eta, src) in MEASURED.items():
        a, scale, dmax = convert(sa, ssp, eta)
        print(f'\t{{"{name}", {fmt3(a)}, {fmt3(scale)}, {dmax:.6g}f}},'
              f'  // {src}, eta={eta}')
    print("\n# Python seed table (SuperBlendLuxCore):")
    for name, (sa, ssp, eta, src) in MEASURED.items():
        a, scale, dmax = convert(sa, ssp, eta)
        a3 = ", ".join(f"{x:.4f}" for x in a)
        s3 = ", ".join(f"{x:.4f}" for x in scale)
        print(f'    "{name}": (({a3}), ({s3}), {dmax:.5f}),')


if __name__ == "__main__":
    main()
