# SPDX-License-Identifier: Apache-2.0
#
# Generates include/luxrays/core/color/spds/data/jh2019_32.h -- the
# Jakob-Hanika 2019 (rgb2spec) sigmoid-basis coefficient table used by the
# opt-in `path.spectral.upsampling = jh2019` mode.
#
# Provenance / regeneration recipe
# ---------------------------------
# The table is produced by the canonical rgb2spec optimizer:
#
#   repo:    https://github.com/mitsuba-renderer/rgb2spec
#   commit:  721145dedf2491851bd46ab8fd165955cb38ddaf
#   license: BSD-3-Clause (c) 2020 Wenzel Jakob <wenzel.jakob@epfl.ch>
#   paper:   W. Jakob, J. Hanika, "A Low-Dimensional Function Space for
#            Efficient Spectral Upsampling", EGSR 2019.
#
# Steps:
#   1. git clone https://github.com/mitsuba-renderer/rgb2spec && cd rgb2spec
#   2. git apply <repo>/dev-tools/rgb2spec_luxcore_gamut.patch
#      (adds a "LUXCORE" gamut to rgb2spec_opt.cpp): the LuxCore
#      ColorSystem::DefaultColorSystem uses SMPTE primaries
#      (xR=.63 yR=.34 xG=.31 yG=.595 xB=.155 yB=.07,
#      white xW=.314275 yW=.329411), NOT sRGB -- see
#      src/luxrays/core/color/color.cpp. The illuminant is CIE E (flat):
#      the same convention the existing Smits reflectance basis
#      (rgbE_32.h) uses, and it also makes the table exact for emission
#      colors (an emitted SPD is observed under a flat illuminant).
#   3. c++ -std=c++14 -O3 -o rgb2spec_opt rgb2spec_opt.cpp -lpthread
#      ./rgb2spec_opt 32 jh2019_luxcore_32.coeff LUXCORE
#   4. python3 dev-tools/gen_jh2019_table.py jh2019_luxcore_32.coeff \
#          > include/luxrays/core/color/spds/data/jh2019_32.h
#
# Resolution: res=32 (3*32^3*3 = 294912 float coefficients, ~1.1 MB
# binary). res=64 (the rgb2spec default, ~9 MB) measurably reduces
# trilinear-interpolation error on saturated colors but is too heavy to
# embed in source; res=32 is the same tradeoff other engines ship at
# similar budgets.
#
# .coeff file layout (see rgb2spec.c rgb2spec_load):
#   "SPEC" magic | uint32 res | float scale[res]
#   | float coeffs[3*res*res*res*3]   # [dominant][z][y][x][coeff]
#   | uint32 nfine | float fwd[4*nfine+12]   (unused, fetch_opt only)

import struct
import sys
import datetime

HEADER = """/***************************************************************************
 * Copyright 1998-2026 by authors (see AUTHORS.txt)                        *
 *                                                                         *
 *   This file is part of LuxCoreRender.                                   *
 *                                                                         *
 *   Licensed under the Apache License, Version 2.0 (the "License");       *
 *   you may not use this file except in compliance with the License.      *
 *   You may obtain a copy of the License at                               *
 *                                                                         *
 *   Unless required by applicable law or agreed to in writing, software   *
 *   distributed under the License is distributed on an "AS IS" BASIS,     *
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or       *
 *   implied.                                                              *
 *   See the License for the specific language governing permissions and   *
 *   limitations under the License.                                        *
 ***************************************************************************/

// Jakob-Hanika 2019 ("A Low-Dimensional Function Space for Efficient
// Spectral Upsampling", W. Jakob & J. Hanika, EGSR 2019) RGB->SPD
// coefficient table for the opt-in `path.spectral.upsampling = jh2019`
// mode.
//
// The model: SPD(lambda) = sigmoid(c0*lambda^2 + c1*lambda + c2) with
// sigmoid(x) = 0.5 + 0.5*x/sqrt(1+x^2) and lambda in nm. The 3
// coefficients per RGB triplet come from this table via the
// dominant-channel trilinear lookup of rgb2spec (see
// Spectral::UpsampleJH2019 in src/luxrays/core/color/spectral.cpp and
// the identical device code in include/slg/spectral_funcs.cl).
//
// Table generated by the rgb2spec optimizer
// (https://github.com/mitsuba-renderer/rgb2spec, BSD-3-Clause,
// (c) 2020 Wenzel Jakob, commit 721145dedf2491851bd46ab8fd165955cb38ddaf)
// at resolution 32, for the LuxCore gamut (ColorSystem::DefaultColorSystem
// SMPTE primaries + white point, illuminant CIE E). See
// dev-tools/gen_jh2019_table.py for the regeneration recipe.
"""


def main(path):
    with open(path, "rb") as f:
        blob = f.read()
    if blob[:4] != b"SPEC":
        raise SystemExit("not a .coeff file (bad magic)")
    res, = struct.unpack_from("<I", blob, 4)
    off = 8
    scale = struct.unpack_from(f"<{res}f", blob, off)
    off += 4 * res
    n_coeffs = 3 * res * res * res * 3
    coeffs = struct.unpack_from(f"<{n_coeffs}f", blob, off)
    off += 4 * n_coeffs
    # trailing nfine/fwd block is not needed (we never run fetch_opt)

    print(HEADER)
    print("namespace luxrays {")
    print("namespace jh2019 {")
    print()
    print(f"static const unsigned int res = {res};")
    print()
    print("// Non-linear dominant-channel (z) quantization: smoothstep^2 grid")
    print(f"static const float scale[{res}] = {{")
    for i in range(0, res, 4):
        print("\t\t" + ", ".join(f"{v:.9e}f" for v in scale[i:i + 4]) +
              ("," if i + 4 < res else ""))
    print("};")
    print()
    print(f"// Sigmoid polynomial coefficients, layout [dominant channel][z][y][x][3]")
    print(f"// ({3 * res * res * res * 3} floats)")
    print(f"static const float coeffs[{n_coeffs}] = {{")
    for i in range(0, n_coeffs, 6):
        print("\t\t" + ", ".join(f"{v:.9e}f" for v in coeffs[i:i + 6]) +
              ("," if i + 6 < n_coeffs else ""))
    print("};")
    print()
    print("} // namespace jh2019")
    print("} // namespace luxrays")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit("usage: gen_jh2019_table.py <input.coeff>")
    main(sys.argv[1])
