# SPDX-License-Identifier: Apache-2.0
#
# Generates include/slg/materials/ggxglass_energy_table.h and the
# matching GGXGLASS_E block in materialdefs_funcs_microfacet.cl.
# Run inside Blender's Python (numpy):
#   Blender -b --factory-startup --python dev-tools/gen_ggx_glass_energy.py -- <out.npy>
#   Blender -b --factory-startup --python dev-tools/gen_ggx_glass_energy.py -- emit <out.npy>
# Single-scatter directional albedo E(rough, mu, z) of a GGX dielectric
# (reflection + transmission, exact Fresnel), Cycles table convention:
# rough = sqrt(alpha), z = sqrt((ior-1)/(ior+1)), ior >= 1 for E, and the
# "inv" table for the exiting side (relative ior 1/ior).
import numpy as np, sys
N = 16; NS = 1 << 15
rng = np.random.default_rng(1234)

def lam(cos, a):
    cos = np.clip(np.abs(cos), 1e-6, 1.0)
    t2 = (1 - cos * cos) / (cos * cos)
    return (-1 + np.sqrt(1 + a * a * t2)) / 2

def vndf(wo, a, u1, u2):
    vh = np.array([a * wo[0], a * wo[1], wo[2]]); vh /= np.linalg.norm(vh)
    lensq = vh[0]**2 + vh[1]**2
    T1 = np.array([-vh[1], vh[0], 0]) / np.sqrt(lensq) if lensq > 0 else np.array([1., 0, 0])
    T2 = np.cross(vh, T1)
    r = np.sqrt(u1); phi = 2 * np.pi * u2
    t1 = r * np.cos(phi); t2 = r * np.sin(phi)
    s = 0.5 * (1 + vh[2]); t2 = (1 - s) * np.sqrt(1 - t1 * t1) + s * t2
    nh = t1[:, None] * T1 + t2[:, None] * T2 + np.sqrt(np.maximum(0, 1 - t1 * t1 - t2 * t2))[:, None] * vh
    n = np.stack([a * nh[:, 0], a * nh[:, 1], np.maximum(1e-6, nh[:, 2])], 1)
    return n / np.linalg.norm(n, axis=1, keepdims=True)

def fresnel(c, eta):  # eta = n_t / n_i
    g2 = eta * eta - 1 + c * c
    tir = g2 < 0
    g = np.sqrt(np.maximum(g2, 0))
    A = (g - c) / (g + c); B = (c * (g + c) - 1) / (c * (g - c) + 1)
    F = 0.5 * A * A * (1 + B * B)
    return np.where(tir, 1.0, np.clip(F, 0, 1))

def E(rough, mu, eta):
    a = max(rough * rough, 1e-4)
    mu = max(mu, 1e-3)
    wo = np.array([np.sqrt(1 - mu * mu), 0, mu])
    u1 = (np.arange(NS) + rng.random(NS)) / NS; u2 = rng.random(NS)
    h = vndf(wo, a, u1, u2)
    c = h @ wo
    F = fresnel(c, eta)
    lo = lam(wo[2], a); g1 = 1 / (1 + lo)
    wr = 2 * c[:, None] * h - wo
    okr = wr[:, 2] > 0
    g2r = 1 / (1 + lo + lam(wr[:, 2], a))
    # refraction (relative eta = n_t/n_i)
    ie = 1 / eta
    k = 1 - ie * ie * (1 - c * c)
    okk = k > 0
    wt = -ie * wo + (ie * c - np.sqrt(np.maximum(k, 0)))[:, None] * h
    okt = okk & (wt[:, 2] < 0)
    g2t = 1 / (1 + lo + lam(wt[:, 2], a))
    val = F * np.where(okr, g2r / g1, 0) + (1 - F) * np.where(okt, g2t / g1, 0)
    return float(val.mean())

def table(inv):
    T = np.zeros((N, N, N), np.float32)
    for iz in range(N):
        z = min(iz / (N - 1), 0.995)
        ior = (1 + z * z) / (1 - z * z)
        eta = 1 / ior if inv else ior
        for ir in range(N):
            for im in range(N):
                T[iz, im, ir] = E(ir / (N - 1), im / (N - 1), eta)
    return T

def _emit(npy):
    import re
    from pathlib import Path
    repo = Path(__file__).resolve().parent.parent
    vals = [float(x) for x in np.load(npy).ravel()]
    body = ",\n".join(", ".join(f"{v:.6f}f" for v in vals[i:i + 8]) for i in range(0, len(vals), 8))
    hdr = ("// SPDX-License-Identifier: Apache-2.0\n// Generated by dev-tools/gen_ggx_glass_energy.py - do not edit.\n"
           "#pragma once\n#define SLG_GGX_GLASS_E_N 16\nnamespace slg {\nstatic const float GgxGlassETable[2 * 16 * 16 * 16] = {\n" + body + "\n};\n}\n")
    (repo / "include/slg/materials/ggxglass_energy_table.h").write_text(hdr)
    cl = repo / "include/slg/materials/materialdefs_funcs_microfacet.cl"
    t = cl.read_text()
    block = "// GGXGLASS_E BEGIN (generated)\n__constant float Microfacet_GgxGlassETable[2 * 16 * 16 * 16] = {\n" + body + "\n};\n// GGXGLASS_E END\n"
    t = re.sub(r"// GGXGLASS_E BEGIN \(generated\)\n.*?// GGXGLASS_E END\n", lambda m: block, t, flags=re.S)
    cl.write_text(t)

if __name__ == "__main__":
    if "--" in sys.argv:
        sys.argv = [sys.argv[0]] + sys.argv[sys.argv.index("--") + 1:]
    if len(sys.argv) > 2 and sys.argv[1] == "emit":
        _emit(sys.argv[2]); sys.exit()
    if len(sys.argv) > 1 and sys.argv[1] == "probe":
        for r in (0.3, 0.6, 1.0):
            print("rough", r, "ior1.4 enter mu.8", round(E(r, .8, 1.4), 4), "exit", round(E(r, .8, 1 / 1.4), 4))
        sys.exit()
    np.save(sys.argv[1], np.stack([table(False), table(True)]))
