"""Finite emitting slabs against an independent radiative-transfer integral.

Run in Python 3.13 or Blender's bundled Python. Checks source integration,
not a rendered-image reference generated by the same implementation.
"""
import hashlib
import json
import os
from pathlib import Path
import sys
import time

import numpy as np

repo = Path(__file__).resolve().parents[1]
sys.path.insert(0, os.environ.get('SLC_EMISSION_MODULE_DIR', str(repo / 'out/build/src/pysuperluxcore/Release')))
import pysuperluxcore as lux

lux.Init()
folder = Path(os.environ['SUPERLUXCORE_AUDIT_DIR'])
folder.mkdir(parents=True, exist_ok=True)
native = getattr(lux, 'pysuperluxcore', lux)
proof = {'complete': False, 'native_sha256': hashlib.sha256(Path(native.__file__).read_bytes()).hexdigest(),
         'harness_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(), 'records': []}


def render(engine, tracking, length, step, absorption):
    scene = lux.Scene()
    props = lux.Properties()
    props.SetFromString(f'''
scene.camera.lookat.orig = 0 0 5
scene.camera.lookat.target = 0 0 0
scene.camera.up = 0 1 0
scene.camera.fieldofview = 0.5
scene.volumes.medium.type = heterogeneous
scene.volumes.medium.absorption = {absorption}
scene.volumes.medium.scattering = 0
scene.volumes.medium.emission = 0.2 0.4 0.6
scene.volumes.medium.asymmetry = 0
scene.volumes.medium.steps.size = {step}
scene.volumes.medium.steps.maxcount = 4096
scene.volumes.medium.tracking = {tracking}
scene.materials.boundary.type = null
scene.materials.boundary.volume.interior = medium
scene.objects.slab.material = boundary
scene.objects.slab.vertices = -2 -2 0 2 -2 0 2 2 0 -2 2 0 -2 -2 {length} 2 -2 {length} 2 2 {length} -2 2 {length}
scene.objects.slab.faces = 0 2 1 0 3 2 4 5 6 4 6 7 0 1 5 0 5 4 1 2 6 1 6 5 2 3 7 2 7 6 3 0 4 3 4 7
''')
    scene.Parse(props)
    cfg = lux.Properties()
    cfg.SetFromString(f'''
renderengine.type = {engine}
film.width = 256
film.height = 256
film.filter.type = NONE
film.imagepipelines.0.0.type = NOP
batch.haltspp = 256
sampler.type = SOBOL
sampler.sobol.adaptive.strength = 0
renderengine.seed = 19
native.threads.count = 4
opencl.native.threads.count = 0
opencl.devices.select = 010
opencl.task.count = 8192
path.lighttracing.enable = 0
path.mnee.enable = 0
path.hybridbackforward.enable = 0
''')
    session = lux.RenderSession(lux.RenderConfig(cfg, scene))
    session.Start()
    try:
        deadline = time.monotonic() + 240
        while True:
            session.UpdateStats()
            if session.HasDone():
                break
            assert time.monotonic() < deadline, (engine, tracking, 'timeout')
            time.sleep(.1)
        rgb = np.empty(256 * 256 * 3, dtype=np.float32)
        session.GetFilm().GetOutputFloat(lux.FilmOutputType.RGB, rgb, 0, True)
    finally:
        session.Stop()
    rgb = rgb.reshape(256, 256, 3)
    assert np.isfinite(rgb).all()
    measured = rgb[80:176, 80:176].mean(axis=(0, 1), dtype=np.float64)
    # Near-orthographic center directions: path-length variation < 0.001%.
    integral = length if absorption == 0 else -np.expm1(-absorption * length) / absorption
    expected = np.array([.2, .4, .6]) * integral
    error = float(np.max(np.abs(measured - expected) / expected))
    record = {'engine': engine, 'tracking': tracking, 'length': length, 'step': step,
              'absorption': absorption, 'measured': measured.tolist(), 'expected': expected.tolist(),
              'relative_error': error, 'limit': .02, 'passed': error < .02}
    proof['records'].append(record)
    (folder / 'metrics.json').write_text(json.dumps(proof, indent=2) + '\n')
    print('EMITTING_SLAB', record, flush=True)
    assert record['passed'], record


for engine in os.environ.get('SLC_EMISSION_ENGINES', 'PATHCPU,PATHOCL').split(','):
    for tracking in ['delta', 'march']:
        for length, step, absorption in [(.5, .05, 0), (2., .2, 0), (2., .01, .4)]:
            render(engine, tracking, length, step, absorption)
proof['complete'] = True
(folder / 'metrics.json').write_text(json.dumps(proof, indent=2) + '\n')
print('EMITTING_SLAB_COMPLETE', flush=True)
